    <div class="row">
      <div class="large_12 column">
        <h1 class="centered">徵戰友</h1>
      </div>
      <div class="large-12 panel column">
        <h3>馬上來徵戰友吧！</h3>
        <p>預見先鋒徵戰友系統強勢上線！搭載最先進最好用的徵戰友系統，幫你找到最適合的戰友！</p>
        <div class="clear"></div>
        <form>
          <div class="row">
            <div class="large-6 column">
              <div class="row collapse">
                <div class="small-7 column">
                  <select>
                    <option value="0">-- 選擇卡片 --</option>
                    <option value="001">No. 001 - 莫莉</option>
                    <option value="002">No. 002 - 高級水術士莫莉</option>
                    <option value="003">No. 003 - 水魔法師莫莉</option>
                    <option value="004">No. 004 - 水元素賢者莫莉</option>
                    <option value="005">No. 005 - 肖恩</option>
                    <option value="006">No. 006 - 高級劍士肖恩</option>
                    <option value="007">No. 007 - 火焰劍士肖恩</option>
                    <option value="008">No. 008 - 紅蓮劍士肖恩</option>
                    <option value="009">No. 009 - 鄧肯</option>
                    <option value="010">No. 010 - 牧者鄧肯</option>
                    <option value="011">No. 011 - 德魯依鄧肯</option>
                    <option value="012">No. 012 - 森林王者鄧肯</option>
                    <option value="013">No. 013 - 男爵奈寶尼</option>
                    <option value="014">No. 014 - 子爵奈寶尼</option>
                    <option value="015">No. 015 - 伯爵奈寶尼</option>
                    <option value="016">No. 016 - 侯爵奈寶尼</option>
                    <option value="017">No. 017 - 暗修導士安多</option>
                    <option value="018">No. 018 - 高級暗修導士安多</option>
                    <option value="019">No. 019 - 死靈術士安多</option>
                    <option value="020">No. 020 - 死靈祭師安多</option>
                    <option value="021">No. 021 - 水方士</option>
                    <option value="022">No. 022 - 清川真人</option>
                    <option value="023">No. 023 - 靈江仙人</option>
                    <option value="024">No. 024 - 青龍孟章神君</option>
                    <option value="025">No. 025 - 火方士</option>
                    <option value="026">No. 026 - 赤灶真人</option>
                    <option value="027">No. 027 - 真火仙人</option>
                    <option value="028">No. 028 - 朱雀陵光神君</option>
                    <option value="029">No. 029 - 木方士</option>
                    <option value="030">No. 030 - 九地真人</option>
                    <option value="031">No. 031 - 虛土仙人</option>
                    <option value="032">No. 032 - 玄武執明神君</option>
                    <option value="033">No. 033 - 陽方士</option>
                    <option value="034">No. 034 - 聖明真人</option>
                    <option value="035">No. 035 - 耀尊仙人</option>
                    <option value="036">No. 036 - 白虎監兵神君</option>
                    <option value="037">No. 037 - 陰方士</option>
                    <option value="038">No. 038 - 幽陵真人</option>
                    <option value="039">No. 039 - 紫微妖仙</option>
                    <option value="040">No. 040 - 饕餮渾沌魔君</option>
                    <option value="041">No. 041 - 冰花龍</option>
                    <option value="042">No. 042 - 冰晶龍</option>
                    <option value="043">No. 043 - 冰晶龍王</option>
                    <option value="044">No. 044 - 洋燭龍</option>
                    <option value="045">No. 045 - 星火龍</option>
                    <option value="046">No. 046 - 硝鐵火龍</option>
                    <option value="047">No. 047 - 碧甲龍</option>
                    <option value="048">No. 048 - 碧甲岩龍</option>
                    <option value="049">No. 049 - 靈山龍龜</option>
                    <option value="050">No. 050 - 光輝龍</option>
                    <option value="051">No. 051 - 閃耀龍</option>
                    <option value="052">No. 052 - 聖衡機龍</option>
                    <option value="053">No. 053 - 無頭龍</option>
                    <option value="054">No. 054 - 斷頭龍</option>
                    <option value="055">No. 055 - 魂索邪龍</option>
                    <option value="056">No. 056 - 冰原地精</option>
                    <option value="057">No. 057 - 淵寒大地精</option>
                    <option value="058">No. 058 - 火山地精</option>
                    <option value="059">No. 059 - 熾岩大地精</option>
                    <option value="060">No. 060 - 森林地精</option>
                    <option value="061">No. 061 - 碧石大地精</option>
                    <option value="062">No. 062 - 光明地精</option>
                    <option value="063">No. 063 - 輝芒大地精</option>
                    <option value="064">No. 064 - 黑暗地精</option>
                    <option value="065">No. 065 - 冥土大地精</option>
                    <option value="066">No. 066 - 海精靈</option>
                    <option value="067">No. 067 - 海躍精靈</option>
                    <option value="068">No. 068 - 火精靈</option>
                    <option value="069">No. 069 - 火舞精靈</option>
                    <option value="070">No. 070 - 花精靈</option>
                    <option value="071">No. 071 - 花冠精靈</option>
                    <option value="072">No. 072 - 月精靈</option>
                    <option value="073">No. 073 - 月光精靈</option>
                    <option value="074">No. 074 - 夜精靈</option>
                    <option value="075">No. 075 - 夜迷精靈</option>
                    <option value="076">No. 076 - 冰蜥蝪戰士</option>
                    <option value="077">No. 077 - 冰河蜥蝪戰士</option>
                    <option value="078">No. 078 - 赤蜥蝪戰士</option>
                    <option value="079">No. 079 - 赤焰蜥蝪戰士</option>
                    <option value="080">No. 080 - 翠蜥蝪戰士</option>
                    <option value="081">No. 081 - 森林蜥蝪戰士</option>
                    <option value="082">No. 082 - 光蜥蝪戰士</option>
                    <option value="083">No. 083 - 金光蜥蝪戰士</option>
                    <option value="084">No. 084 - 暗蜥蝪戰士</option>
                    <option value="085">No. 085 - 漆黑蜥蝪戰士</option>
                    <option value="086">No. 086 - 小魔女愛莉絲</option>
                    <option value="087">No. 087 - 占星士愛莉絲</option>
                    <option value="088">No. 088 - 小魔女瑪莉曼</option>
                    <option value="089">No. 089 - 火巫女瑪莉曼</option>
                    <option value="090">No. 090 - 小魔女凱莉絲</option>
                    <option value="091">No. 091 - 修道者凱莉絲</option>
                    <option value="092">No. 092 - 小魔女安迪莉亞</option>
                    <option value="093">No. 093 - 傳教士安迪莉亞</option>
                    <option value="094">No. 094 - 小魔女莉莉絲</option>
                    <option value="095">No. 095 - 鍊金士莉莉絲</option>
                    <option value="096">No. 096 - 水史萊姆</option>
                    <option value="097">No. 097 - 液態史萊姆</option>
                    <option value="098">No. 098 - 火史萊姆</option>
                    <option value="099">No. 099 - 燃燒史萊姆</option>
                    <option value="100">No. 100 - 木史萊姆</option>
                    <option value="101">No. 101 - 翠綠史萊姆</option>
                    <option value="102">No. 102 - 光史萊姆</option>
                    <option value="103">No. 103 - 天使史萊姆</option>
                    <option value="104">No. 104 - 暗史萊姆</option>
                    <option value="105">No. 105 - 幽靈史萊姆</option>
                    <option value="106">No. 106 - 蒼幽狼</option>
                    <option value="107">No. 107 - 蒼幽狼人</option>
                    <option value="108">No. 108 - 赤幽狼</option>
                    <option value="109">No. 109 - 赤幽狼人</option>
                    <option value="110">No. 110 - 青幽狼</option>
                    <option value="111">No. 111 - 青幽狼人</option>
                    <option value="112">No. 112 - 白幽狼</option>
                    <option value="113">No. 113 - 白幽狼人</option>
                    <option value="114">No. 114 - 黑幽狼</option>
                    <option value="115">No. 115 - 黑幽狼人</option>
                    <option value="116">No. 116 - 烏爾德</option>
                    <option value="117">No. 117 - 過去之烏爾德</option>
                    <option value="118">No. 118 - 歷史之烏爾德</option>
                    <option value="119">No. 119 - 斯庫爾德</option>
                    <option value="120">No. 120 - 未來之斯庫爾德</option>
                    <option value="121">No. 121 - 無常之斯庫爾德</option>
                    <option value="122">No. 122 - 薇兒丹蒂</option>
                    <option value="123">No. 123 - 現在之薇兒丹蒂</option>
                    <option value="124">No. 124 - 命運之薇兒丹蒂</option>
                    <option value="125">No. 125 - 伊登</option>
                    <option value="126">No. 126 - 聖果之伊登</option>
                    <option value="127">No. 127 - 永生之伊登</option>
                    <option value="128">No. 128 - 英靈殿侍女</option>
                    <option value="129">No. 129 - 戰魂之瓦爾基麗</option>
                    <option value="130">No. 130 - 催魂之瓦爾基麗</option>
                    <option value="131">No. 131 - 水遊俠</option>
                    <option value="132">No. 132 - 水舞劍士</option>
                    <option value="133">No. 133 - 水舞劍神</option>
                    <option value="134">No. 134 - 火遊俠</option>
                    <option value="135">No. 135 - 火焰戰士</option>
                    <option value="136">No. 136 - 炎舞軍神</option>
                    <option value="137">No. 137 - 木遊俠</option>
                    <option value="138">No. 138 - 翠綠狙擊手</option>
                    <option value="139">No. 139 - 疾風神射手</option>
                    <option value="140">No. 140 - 光遊俠</option>
                    <option value="141">No. 141 - 聖光遊俠</option>
                    <option value="142">No. 142 - 萬劍遊俠</option>
                    <option value="143">No. 143 - 暗遊俠</option>
                    <option value="144">No. 144 - 暗夜刺客</option>
                    <option value="145">No. 145 - 暗影劍豪</option>
                    <option value="146">No. 146 - 冰耀巨像</option>
                    <option value="147">No. 147 - 冰耀巨像 ‧ 解放</option>
                    <option value="148">No. 148 - 冰耀巨鱷</option>
                    <option value="149">No. 149 - 烙紅巨像</option>
                    <option value="150">No. 150 - 烙紅巨像 ‧ 解放</option>
                    <option value="151">No. 151 - 烙紅龍蜥</option>
                    <option value="152">No. 152 - 碧青巨像</option>
                    <option value="153">No. 153 - 碧青巨像 ‧ 解放</option>
                    <option value="154">No. 154 - 碧青行者</option>
                    <option value="155">No. 155 - 聖靈巨像</option>
                    <option value="156">No. 156 - 聖靈巨像 ‧ 解放</option>
                    <option value="157">No. 157 - 聖靈怒獅</option>
                    <option value="158">No. 158 - 暗月巨像</option>
                    <option value="159">No. 159 - 暗月巨像 ‧ 解放</option>
                    <option value="160">No. 160 - 暗月夜龍</option>
                    <option value="161">No. 161 - 機械鯨鯊</option>
                    <option value="162">No. 162 - 強化機械鯨鯊</option>
                    <option value="163">No. 163 - 變異機械鯨鯊</option>
                    <option value="164">No. 164 - 機械獅子</option>
                    <option value="165">No. 165 - 強化機械獅子</option>
                    <option value="166">No. 166 - 狂暴機械獅子</option>
                    <option value="167">No. 167 - 機械犀牛</option>
                    <option value="168">No. 168 - 強化機械犀牛</option>
                    <option value="169">No. 169 - 野蠻機械犀牛</option>
                    <option value="170">No. 170 - 機械狼</option>
                    <option value="171">No. 171 - 強化機械狼</option>
                    <option value="172">No. 172 - 重甲機械狼</option>
                    <option value="173">No. 173 - 機械豹</option>
                    <option value="174">No. 174 - 強化機械豹</option>
                    <option value="175">No. 175 - 掠奪機械豹</option>
                    <option value="176">No. 176 - 海獸</option>
                    <option value="177">No. 177 - 克蘇魯</option>
                    <option value="178">No. 178 - 邪神克蘇魯</option>
                    <option value="179">No. 179 - 地獄三頭犬</option>
                    <option value="180">No. 180 - 基路比魯斯</option>
                    <option value="181">No. 181 - 冥府兇獸基路比魯斯</option>
                    <option value="182">No. 182 - 蛇妖</option>
                    <option value="183">No. 183 - 美杜莎</option>
                    <option value="184">No. 184 - 妖女美杜莎</option>
                    <option value="185">No. 185 - 鷹頭獸</option>
                    <option value="186">No. 186 - 獅鷲</option>
                    <option value="187">No. 187 - 獅鷲獸王</option>
                    <option value="188">No. 188 - 魔羊</option>
                    <option value="189">No. 189 - 魔羊怪</option>
                    <option value="190">No. 190 - 惡魔巴風特</option>
                    <option value="191">No. 191 - 波塞頓</option>
                    <option value="192">No. 192 - 海神波塞頓</option>
                    <option value="193">No. 193 - 赫淮斯托斯</option>
                    <option value="194">No. 194 - 奧林火神赫淮斯托斯</option>
                    <option value="195">No. 195 - 雅典娜</option>
                    <option value="196">No. 196 - 智慧女神雅典娜</option>
                    <option value="197">No. 197 - 阿波羅</option>
                    <option value="198">No. 198 - 光明之神阿波羅</option>
                    <option value="199">No. 199 - 阿提密斯</option>
                    <option value="200">No. 200 - 月之狩獵女神阿提密斯</option>
                    <option value="201">No. 201 - 費雷</option>
                    <option value="202">No. 202 - 勝利海神費雷</option>
                    <option value="203">No. 203 - 提爾</option>
                    <option value="204">No. 204 - 獨臂戰神提爾</option>
                    <option value="205">No. 205 - 費蕾雅</option>
                    <option value="206">No. 206 - 妙曼愛神費蕾雅</option>
                    <option value="207">No. 207 - 索爾</option>
                    <option value="208">No. 208 - 轟天雷神索爾</option>
                    <option value="209">No. 209 - 洛基</option>
                    <option value="210">No. 210 - 黃昏號角洛基</option>
                    <option value="211">No. 211 - 泰芙努特</option>
                    <option value="212">No. 212 - 雨神泰芙努特</option>
                    <option value="213">No. 213 - 賽特</option>
                    <option value="214">No. 214 - 戰爭之神賽特</option>
                    <option value="215">No. 215 - 舒</option>
                    <option value="216">No. 216 - 天空之神 ‧ 舒</option>
                    <option value="217">No. 217 - 拉</option>
                    <option value="218">No. 218 - 太陽之子拉</option>
                    <option value="219">No. 219 - 奧西利斯</option>
                    <option value="220">No. 220 - 不死冥王奧西利斯</option>
                    <option value="221">No. 221 - 海龍</option>
                    <option value="222">No. 222 - 東海龍王 ‧ 敖廣</option>
                    <option value="223">No. 223 - 蓮藕仔</option>
                    <option value="224">No. 224 - 三太子 ‧ 哪吒</option>
                    <option value="225">No. 225 - 大力王</option>
                    <option value="226">No. 226 - 平天大聖 ‧ 牛魔王</option>
                    <option value="227">No. 227 - 美猴王</option>
                    <option value="228">No. 228 - 齊天大聖 ‧ 孫悟空</option>
                    <option value="229">No. 229 - 妖狐</option>
                    <option value="230">No. 230 - 白臉金毛 ‧ 妲己</option>
                    <option value="231">No. 231 - 機械水龍</option>
                    <option value="232">No. 232 - 機械水神龍 ‧ 內拉羅斯</option>
                    <option value="233">No. 233 - 機械火龍</option>
                    <option value="234">No. 234 - 機械火神龍 ‧ 伊索爾德</option>
                    <option value="235">No. 235 - 機械地龍</option>
                    <option value="236">No. 236 - 機械地神龍 ‧ 卡斯迪</option>
                    <option value="237">No. 237 - 機械聖龍</option>
                    <option value="238">No. 238 - 機械聖皇龍 ‧ 泰瑞那斯</option>
                    <option value="239">No. 239 - 機械闇龍</option>
                    <option value="240">No. 240 - 機械冥王龍 ‧ 萊瑞姆</option>
                    <option value="241">No. 241 - 破碎之蒼魂</option>
                    <option value="242">No. 242 - 破碎之赤魂</option>
                    <option value="243">No. 243 - 破碎之青魂</option>
                    <option value="244">No. 244 - 破碎之白魂</option>
                    <option value="245">No. 245 - 破碎之黑魂</option>
                    <option value="246">No. 246 - 重生之蒼魂</option>
                    <option value="247">No. 247 - 重生之赤魂</option>
                    <option value="248">No. 248 - 重生之青魂</option>
                    <option value="249">No. 249 - 重生之白魂</option>
                    <option value="250">No. 250 - 重生之黑魂</option>
                    <option value="251">No. 251 - 共生之蒼魂</option>
                    <option value="252">No. 252 - 共生之赤魂</option>
                    <option value="253">No. 253 - 共生之青魂</option>
                    <option value="254">No. 254 - 共生之白魂</option>
                    <option value="255">No. 255 - 共生之黑魂</option>
                    <option value="256">No. 256 - 永恆之蒼魂</option>
                    <option value="257">No. 257 - 永恆之赤魂</option>
                    <option value="258">No. 258 - 永恆之青魂</option>
                    <option value="259">No. 259 - 永恆之白魂</option>
                    <option value="260">No. 260 - 永恆之黑魂</option>
                    <option value="261">No. 261 - 水晶龍蛋</option>
                    <option value="262">No. 262 - 破殼水晶龍</option>
                    <option value="263">No. 263 - 稀有水晶龍</option>
                    <option value="264">No. 264 - 詛咒之劍</option>
                    <option value="265">No. 265 - 殺戮之劍</option>
                    <option value="266">No. 266 - 魔神之劍</option>
                    <option value="267">No. 267 - 蜜涎獸</option>
                    <option value="268">No. 268 - 蜜羽獸</option>
                    <option value="269">No. 269 - 蜜月獸</option>
                    <option value="270">No. 270 - 海洋小靈魂石</option>
                    <option value="271">No. 271 - 火焰小靈魂石</option>
                    <option value="272">No. 272 - 大地小靈魂石</option>
                    <option value="273">No. 273 - 神聖小靈魂石</option>
                    <option value="274">No. 274 - 鬼魅小靈魂石</option>
                    <option value="275">No. 275 - 海洋靈魂石</option>
                    <option value="276">No. 276 - 火焰靈魂石</option>
                    <option value="277">No. 277 - 大地靈魂石</option>
                    <option value="278">No. 278 - 神聖靈魂石</option>
                    <option value="279">No. 279 - 鬼魅靈魂石</option>
                    <option value="280">No. 280 - 海洋千年靈魂石</option>
                    <option value="281">No. 281 - 火焰千年靈魂石</option>
                    <option value="282">No. 282 - 大地千年靈魂石</option>
                    <option value="283">No. 283 - 神聖千年靈魂石</option>
                    <option value="284">No. 284 - 鬼魅千年靈魂石</option>
                    <option value="285">No. 285 - 元素操縱者 ‧ 迪亞布羅</option>
                    <option value="286">No. 286 - 萬魔之王 ‧ 薩魯曼</option>
                    <option value="287">No. 287 - 碑紋騎士 ‧ 奧丁</option>
                    <option value="288">No. 288 - 雙體共生 ‧ 噬日狼</option>
                    <option value="289">No. 289 - 雙體共生 ‧ 喰月狼</option>
                    <option value="290">No. 290 - 雖死猶在 ‧ 毒龍尼德霍格</option>
                    <option value="291">No. 291 - 鬼魅萬年靈魂石</option>
                    <option value="292">No. 292 - 人面怪鳥</option>
                    <option value="293">No. 293 - 米迦勒 ‧ 路西法</option>
                    <option value="294">No. 294 - 通透的蛋</option>
                    <option value="295">No. 295 - 海拉</option>
                    <option value="296">No. 296 - 幻夢魚仙 ‧ 伊德海拉</option>
                    <option value="297">No. 297 - 火紅的蛋</option>
                    <option value="298">No. 298 - 梅格</option>
                    <option value="299">No. 299 - 龍裔 ‧ 梅格蘭斯</option>
                    <option value="300">No. 300 - 翠綠的蛋</option>
                    <option value="301">No. 301 - 伊薇特</option>
                    <option value="302">No. 302 - 蝶妖伊薇特</option>
                    <option value="303">No. 303 - 閃亮的蛋</option>
                    <option value="304">No. 304 - 瑪格</option>
                    <option value="305">No. 305 - 聖蜂后 ‧ 瑪格莉特</option>
                    <option value="306">No. 306 - 暗啞的蛋</option>
                    <option value="307">No. 307 - 伊莎貝爾</option>
                    <option value="308">No. 308 - 黑寡婦伊莎貝爾</option>
                    <option value="309">No. 309 - 水之異界龍</option>
                    <option value="310">No. 310 - 深潛者之父 ‧ 達貢</option>
                    <option value="311">No. 311 - 火之異界龍</option>
                    <option value="312">No. 312 - 火焰共生者 ‧ 克圖格亞</option>
                    <option value="313">No. 313 - 風之異界龍</option>
                    <option value="314">No. 314 - 不朽尖吼者 ‧ 拜亞基</option>
                    <option value="315">No. 315 - 光之異界龍</option>
                    <option value="316">No. 316 - 招蕩的輝芒 ‧ 圖爾茲查</option>
                    <option value="317">No. 317 - 暗之異界龍</option>
                    <option value="318">No. 318 - 群山中之恐怖 ‧ 法格恩</option>
                    <option value="319">No. 319 - 破損的海神守護石像</option>
                    <option value="320">No. 320 - 海神守護石像</option>
                    <option value="321">No. 321 - 破損的火神守護石像</option>
                    <option value="322">No. 322 - 火神守護石像</option>
                    <option value="323">No. 323 - 破損的女戰神守護石像</option>
                    <option value="324">No. 324 - 女戰神守護石像</option>
                    <option value="325">No. 325 - 破損的太陽神守護石像</option>
                    <option value="326">No. 326 - 太陽神守護石像</option>
                    <option value="327">No. 327 - 破損的月神守護石像</option>
                    <option value="328">No. 328 - 月神守護石像</option>
                    <option value="329">No. 329 - 浪濤史萊姆</option>
                    <option value="330">No. 330 - 烈炎史萊姆</option>
                    <option value="331">No. 331 - 花豔史萊姆</option>
                    <option value="332">No. 332 - 神聖史萊姆</option>
                    <option value="333">No. 333 - 邪魔史萊姆</option>
                    <option value="334">No. 334 - 海韻女皇</option>
                    <option value="335">No. 335 - 火岩領主</option>
                    <option value="336">No. 336 - 花冠貴婦</option>
                    <option value="337">No. 337 - 月耀公主</option>
                    <option value="338">No. 338 - 夜影魔女</option>
                    <option value="339">No. 339 - 冰谷蜥蝪騎士</option>
                    <option value="340">No. 340 - 岩漿蜥蝪騎士</option>
                    <option value="341">No. 341 - 密林蜥蝪騎士</option>
                    <option value="342">No. 342 - 聖光蜥蝪騎士</option>
                    <option value="343">No. 343 - 黑雷蜥蝪騎士</option>
                    <option value="344">No. 344 - 特洛伊公主</option>
                    <option value="345">No. 345 - 受詛咒的先知 ‧ 卡珊德拉</option>
                    <option value="346">No. 346 - 科耳喀斯皇女</option>
                    <option value="347">No. 347 - 愛與恨的魔女 ‧ 美狄亞</option>
                    <option value="348">No. 348 - 薩爾瑪提亞女皇</option>
                    <option value="349">No. 349 - 黑魔法女巫 ‧ 喀耳刻</option>
                    <option value="350">No. 350 - 寒霧劍塚 ‧ 卡戎</option>
                    <option value="351">No. 351 - 機關傀儡 ‧ 紅月</option>
                    <option value="352">No. 352 - 腐林魔女 ‧ 布萊爾</option>
                    <option value="353">No. 353 - 鐵處女像 ‧ 浮士德</option>
                    <option value="354">No. 354 - 貓公爵 ‧ 費利克斯</option>
                    <option value="355">No. 355 - 持劍侍女 ‧ 波比</option>
                    <option value="356">No. 356 - 白羊宮 ‧ 波比</option>
                    <option value="357">No. 357 - 攻城者 ‧ 阿姆士唐</option>
                    <option value="358">No. 358 - 金牛宮 ‧ 阿姆士唐</option>
                    <option value="359">No. 359 - 雙劍士 ‧ 波魯克斯</option>
                    <option value="360">No. 360 - 雙子宮 ‧ 加斯陀與波魯克斯</option>
                    <option value="361">No. 361 - 暗影刺客 ‧ 約翰</option>
                    <option value="362">No. 362 - 巨蟹宮 ‧ 約翰</option>
                    <option value="363">No. 363 - 重劍士 ‧ 加里昂</option>
                    <option value="364">No. 364 - 獅子宮 ‧ 加里昂</option>
                    <option value="365">No. 365 - 割穗少女 ‧ 普西芬妮</option>
                    <option value="366">No. 366 - 處女宮 ‧ 普西芬妮</option>
                    <option value="367">No. 367 - 聖殿武士 ‧ 露娜</option>
                    <option value="368">No. 368 - 天秤宮 ‧ 露娜</option>
                    <option value="369">No. 369 - 重鐮刺客 ‧ 艾瑪</option>
                    <option value="370">No. 370 - 天蠍宮 ‧ 艾瑪</option>
                    <option value="371">No. 371 - 綠林行者 ‧ 赫茲</option>
                    <option value="372">No. 372 - 人馬宮 ‧ 赫茲</option>
                    <option value="373">No. 373 - 碎岩武者 ‧ 杜門</option>
                    <option value="374">No. 374 - 山羊宮 ‧ 杜門</option>
                    <option value="375">No. 375 - 鬼魅舞者 ‧ 凱莉</option>
                    <option value="376">No. 376 - 水瓶宮 ‧ 凱莉</option>
                    <option value="377">No. 377 - 海浪騎士 ‧ 卡秋婭與拉维妮斯</option>
                    <option value="378">No. 378 - 雙魚宮 ‧ 卡秋婭與拉维妮斯</option>
                    <option value="379">No. 379 - 黃道星靈 ‧ 水</option>
                    <option value="380">No. 380 - 黃道星靈 ‧ 火</option>
                    <option value="381">No. 381 - 黃道星靈 ‧ 木</option>
                    <option value="382">No. 382 - 黃道星靈 ‧ 光</option>
                    <option value="383">No. 383 - 黃道星靈 ‧ 暗</option>
                    <option value="384">No. 384 - 占星者</option>
                    <option value="385">No. 385 - 見習小丑</option>
                    <option value="386">No. 386 - 無頭小丑</option>
                    <option value="387">No. 387 - 午夜之丑角</option>
                    <option value="388">No. 388 - 不懼的鬼戰士</option>
                    <option value="389">No. 389 - 屠龍者 ‧ 貝奧武夫</option>
                    <option value="390">No. 390 - 不仁的鬼鬥士</option>
                    <option value="391">No. 391 - 戰神 ‧ 阿基里斯</option>
                    <option value="392">No. 392 - 不幸的鬼騎士</option>
                    <option value="393">No. 393 - 薔薇雙槍 ‧ 迪爾姆德</option>
                    <option value="394">No. 394 - 不惑的鬼武士</option>
                    <option value="395">No. 395 - 遮那王 ‧ 源義經</option>
                    <option value="396">No. 396 - 不義的鬼將士</option>
                    <option value="397">No. 397 - 鬼神 ‧ 呂布</option>
                    <option value="398">No. 398 - 光輝萬年靈魂石</option>
                    <option value="399">No. 399 - 暴食史萊姆王</option>
                    <option value="400">No. 400 - 瘋頭</option>
                    <option value="401">No. 401 - 聖言歌姬 ‧ 妍</option>
                    <option value="402">No. 402 - 夜言歌姬 ‧ 希</option>
                    <option value="403">No. 403 - 波拉</option>
                    <option value="404">No. 404 - 奇美拉</option>
                    <option value="405">No. 405 - 潘</option>
                    <option value="406">No. 406 - 福魯斯</option>
                    <option value="407">No. 407 - 拉彌亞</option>
                    <option value="408">No. 408 - 大魔導士莫莉</option>
                    <option value="409">No. 409 - 龍焰騎士肖恩</option>
                    <option value="410">No. 410 - 大地霸主鄧肯</option>
                    <option value="411">No. 411 - 公爵奈寶尼</option>
                    <option value="412">No. 412 - 死靈魔導安多</option>
                    <option value="413">No. 413 - 蒼龍魂使</option>
                    <option value="414">No. 414 - 龍儀姬 ‧ 烏蘇拉</option>
                    <option value="415">No. 415 - 赤龍魂使</option>
                    <option value="416">No. 416 - 龍儀姬 ‧ 愛格德</option>
                    <option value="417">No. 417 - 青龍魂使</option>
                    <option value="418">No. 418 - 龍儀姬 ‧ 芭芭拉</option>
                    <option value="419">No. 419 - 光龍魂使</option>
                    <option value="420">No. 420 - 龍脈者 ‧ 安納</option>
                    <option value="421">No. 421 - 暗龍魂使</option>
                    <option value="422">No. 422 - 龍脈者 ‧ 諾瓦利斯</option>
                    <option value="423">No. 423 - 異域法眼</option>
                    <option value="424">No. 424 - 機關騎士</option>
                    <option value="425">No. 425 - 永劫碑文像</option>
                    <option value="426">No. 426 - 碧海萬年靈魂石</option>
                    <option value="427">No. 427 - 熾焰萬年靈魂石</option>
                    <option value="428">No. 428 - 大地萬年靈魂石</option>
                    <option value="429">No. 429 - 追憶旅人</option>
                    <option value="430">No. 430 - 號角手加拉爾</option>
                    <option value="431">No. 431 - 貪婪精靈女王</option>
                    <option value="432">No. 432 - 奪寶海盜</option>
                    <option value="433">No. 433 - 冰晶領航者 ‧ 奪寶海盜</option>
                    <option value="434">No. 434 - 紅纓武者</option>
                    <option value="435">No. 435 - 火靈之舞 ‧ 紅纓武者</option>
                    <option value="436">No. 436 - 捕風酋長</option>
                    <option value="437">No. 437 - 翡翠獵手 ‧ 捕風酋長</option>
                    <option value="438">No. 438 - 清泉守衛</option>
                    <option value="439">No. 439 - 炎鎧戰士</option>
                    <option value="440">No. 440 - 雁目射手</option>
                    <option value="441">No. 441 - 萬劍寵僕</option>
                    <option value="442">No. 442 - 暗影鬥士</option>
                    <option value="443">No. 443 - 占星蛙法師</option>
                    <option value="444">No. 444 - 道法飄蟲</option>
                    <option value="445">No. 445 - 修道雛鴨</option>
                    <option value="446">No. 446 - 賜福蜜蜂</option>
                    <option value="447">No. 447 - 奧秘魚術士</option>
                    <option value="448">No. 448 - 符靈典範 ‧ 綠茵國王</option>
                    <option value="449">No. 449 - 狂怒蜥蝪暴君</option>
                    <option value="450">No. 450 - 法則女神 ‧ 姬氏</option>
                    <option value="451">No. 451 - 地精絞殺者</option>
                    <option value="452">No. 452 - 地精斬首者</option>
                    <option value="453">No. 453 - 地精扼喉者</option>
                    <option value="454">No. 454 - 地精碎骨者</option>
                    <option value="455">No. 455 - 地精切裂者</option>
                    <option value="456">No. 456 - 星佑法師愛莉絲</option>
                    <option value="457">No. 457 - 管狐飼者瑪莉曼</option>
                    <option value="458">No. 458 - 煉屍術士凱莉絲</option>
                    <option value="459">No. 459 - 神罰使者安迪莉亞</option>
                    <option value="460">No. 460 - 鍊金巫師莉莉絲</option>
                    <option value="461">No. 461 - 冽霜武僧</option>
                    <option value="462">No. 462 - 岩焰統領</option>
                    <option value="463">No. 463 - 木靈栽者</option>
                    <option value="464">No. 464 - 聖裁勇者</option>
                    <option value="465">No. 465 - 暗影刺客</option>
                    <option value="466">No. 466 - 貴族伊莉莎白</option>
                    <option value="467">No. 467 - 血浴美人 ‧ 伊莉莎白</option>
                    <option value="468">No. 468 - 信差潔琪</option>
                    <option value="469">No. 469 - 彈簧腿 ‧ 潔琪</option>
                    <option value="470">No. 470 - 婚約者貝莉</option>
                    <option value="471">No. 471 - 罌花新娘 ‧ 貝莉</option>
                    <option value="472">No. 472 - 紳士傑克</option>
                    <option value="473">No. 473 - 開膛怪傑 ‧ 傑克</option>
                    <option value="474">No. 474 - 理髮魔偶陶德</option>
                    <option value="475">No. 475 - 戲謔小丑 ‧ 陶德</option>
                    <option value="476">No. 476 - 冰雪巫師 ‧ 波葛</option>
                    <option value="477">No. 477 - 惡作劇精靈 ‧ 波加特</option>
                    <option value="478">No. 478 - 掃除小精靈 ‧ 布朗尼</option>
                    <option value="479">No. 479 - 沉思的賢者 ‧ 山特古羅斯</option>
                    <option value="480">No. 480 - 色慾胎飼魔母</option>
                    <option value="481">No. 481 - 記憶與遺忘 ‧ 女武神烏爾德</option>
                    <option value="482">No. 482 - 開端與終結 ‧ 女武神斯庫爾德</option>
                    <option value="483">No. 483 - 命定與改變 ‧ 女武神薇兒丹蒂</option>
                    <option value="484">No. 484 - 神木之眷 ‧ 永祭之伊登</option>
                    <option value="485">No. 485 - 破刃之鐮 ‧ 布倫希爾德</option>
                    <option value="486">No. 486 - 水龍牙棋</option>
                    <option value="487">No. 487 - 火龍牙棋</option>
                    <option value="488">No. 488 - 木龍牙棋</option>
                    <option value="489">No. 489 - 光龍牙棋</option>
                    <option value="490">No. 490 - 暗龍牙棋</option>
                    <option value="491">No. 491 - 仰望者瘋帽</option>
                    <option value="492">No. 492 - 狂人三月兔</option>
                    <option value="493">No. 493 - 建言者書頁蟲</option>
                    <option value="494">No. 494 - 餐桌騎士睡鼠</option>
                    <option value="495">No. 495 - 魔郡咧齒貓</option>
                    <option value="496">No. 496 - 魔境之主 ‧ 紅心女王</option>
                    <option value="497">No. 497 - 笑容守護犬</option>
                    <option value="498">No. 498 - 福德神寵 ‧ 笑犬</option>
                    <option value="499">No. 499 - 怒顏守護犬</option>
                    <option value="500">No. 500 - 懲惡神衛 ‧ 怒犬</option>
                    <option value="501">No. 501 - 韶光仙獸 ‧ 年</option>
                    <option value="502">No. 502 - 覓果幻獸</option>
                    <option value="503">No. 503 - 原始滄龍</option>
                    <option value="506">No. 506 - 不滅戰意 ‧ 費雷</option>
                    <option value="507">No. 507 - 烈火懲責 ‧ 提爾</option>
                    <option value="508">No. 508 - 唁魂之喚 ‧ 費蕾雅</option>
                    <option value="509">No. 509 - 轟雷鳴動 ‧ 索爾</option>
                    <option value="510">No. 510 - 不赦眚惡 ‧ 洛基</option>
                    <option value="511">No. 511 - 乾坎天帝 ‧ 青龍</option>
                    <option value="512">No. 512 - 坎艮神鳥 ‧ 朱雀</option>
                    <option value="513">No. 513 - 震巽靈帝 ‧ 玄武</option>
                    <option value="514">No. 514 - 离坤獸皇 ‧ 白虎</option>
                    <option value="515">No. 515 - 兌中邪帝 ‧ 饕餮</option>
                    <option value="516">No. 516 - 復活火鳥</option>
                    <option value="517">No. 517 - 魅影劍客</option>
                    <option value="518">No. 518 - 靈光飛刀手</option>
                    <option value="519">No. 519 - 生命之光 ‧ 伊施妲</option>
                    <option value="520">No. 520 - 傲慢幽狼酋長</option>
                    <option value="521">No. 521 - 蝦兵 ‧ 蟹將</option>
                    <option value="522">No. 522 - 甲兵 ‧ 鎧將</option>
                    <option value="523">No. 523 - 修道客</option>
                    <option value="524">No. 524 - 崑崙道士</option>
                    <option value="525">No. 525 - 桃木精</option>
                    <option value="526">No. 526 - 千里眼</option>
                    <option value="527">No. 527 - 尋道者</option>
                    <option value="528">No. 528 - 散仙神女</option>
                    <option value="529">No. 529 - 柳鬼</option>
                    <option value="530">No. 530 - 順風耳</option>
                    <option value="531">No. 531 - 太師聞仲</option>
                    <option value="532">No. 532 - 普化天尊 ‧ 聞仲</option>
                    <option value="533">No. 533 - 道僧燃燈</option>
                    <option value="534">No. 534 - 錠光如來 ‧ 燃燈</option>
                    <option value="535">No. 535 - 靈將楊戩</option>
                    <option value="536">No. 536 - 清源仙將 ‧ 楊戩</option>
                    <option value="537">No. 537 - 仙道姜尚</option>
                    <option value="538">No. 538 - 封神仙帥 ‧ 姜子牙</option>
                    <option value="539">No. 539 - 仙道申公豹</option>
                    <option value="540">No. 540 - 號雷鬥罡 ‧ 申公豹</option>
                    <option value="541">No. 541 - 傀儡仙童</option>
                    <option value="542">No. 542 - 三清祖師 ‧ 元始天尊</option>
                    <option value="543">No. 543 - 靈寶天尊 ‧ 通天教主</option>
                    <option value="546">No. 546 - 諾弗 ‧ 刻</option>
                    <option value="547">No. 547 - 腹蛇異兵</option>
                    <option value="548">No. 548 - 異神之胎</option>
                    <option value="549">No. 549 - 銀曉信徒</option>
                    <option value="550">No. 550 - 噬土魔蟲</option>
                    <option value="551">No. 551 - 深潛的異族</option>
                    <option value="552">No. 552 - 深潛者之僕 ‧ 蟆鰣</option>
                    <option value="553">No. 553 - 魔焰吸血鬼</option>
                    <option value="554">No. 554 - 永焰之渴 ‧ 唐納德</option>
                    <option value="555">No. 555 - 巨蟾異獸</option>
                    <option value="556">No. 556 - 食魂魔蟾 ‧ 札特瓜</option>
                    <option value="557">No. 557 - 幻神化身</option>
                    <option value="558">No. 558 - 幻夢古神 ‧ 諾斯登</option>
                    <option value="559">No. 559 - 異域蟲族</option>
                    <option value="560">No. 560 - 門鑰之僕 ‧ 米戈</option>
                    <option value="562">No. 562 - 黃衣魅影 ‧ 哈斯塔</option>
                  </select>
                </div>
                <div class="small-5 column">
                  <button class="postfix" type="submit" value="0">找戰友！</button>
                </div>
              </div>
            </div>
            <div class="large-6 column">
              <div class="row collapse">
                <div class="small-7 column">
                  <input type="text" placeholder="依 ID 搜尋"></input>
                </div>
                <div class="small-5 column">
                  <button class="postfix" type="submit" value="1">找戰友！</button>
                </div>
              </div>
            </div>
          </div>
        </form> 
      </div>
      <div class="large-12 panel column">
        <h3>刊登自己的代表</h3>
        <p>請先登入</a>
        <div class="clear"></div>
        <a class="button medium radius" href="./login.html">登入/註冊</a>
        </div>
      </div>
    </div>
