<?php
if(!defined('IN_MOUGE'))
  die("Access Denied");

function showCardList($id)
{
echo "<option value=\"1\"";
if($id == 1) echo "selected=\"selected\"";
echo ">No.1 - 莫莉 （2星）</option>";
echo "<option value=\"2\"";
if($id == 2) echo "selected=\"selected\"";
echo ">No.2 - 高級水術士莫莉 （3星）</option>";
echo "<option value=\"3\"";
if($id == 3) echo "selected=\"selected\"";
echo ">No.3 - 水魔法師莫莉 （4星）</option>";
echo "<option value=\"4\"";
if($id == 4) echo "selected=\"selected\"";
echo ">No.4 - 水元素賢者莫莉 （5星）</option>";
echo "<option value=\"5\"";
if($id == 5) echo "selected=\"selected\"";
echo ">No.5 - 肖恩 （2星）</option>";
echo "<option value=\"6\"";
if($id == 6) echo "selected=\"selected\"";
echo ">No.6 - 高級劍士肖恩 （3星）</option>";
echo "<option value=\"7\"";
if($id == 7) echo "selected=\"selected\"";
echo ">No.7 - 火焰劍士肖恩 （4星）</option>";
echo "<option value=\"8\"";
if($id == 8) echo "selected=\"selected\"";
echo ">No.8 - 紅蓮劍士肖恩 （5星）</option>";
echo "<option value=\"9\"";
if($id == 9) echo "selected=\"selected\"";
echo ">No.9 - 鄧肯 （2星）</option>";
echo "<option value=\"10\"";
if($id == 10) echo "selected=\"selected\"";
echo ">No.10 - 牧者鄧肯 （3星）</option>";
echo "<option value=\"11\"";
if($id == 11) echo "selected=\"selected\"";
echo ">No.11 - 德魯依鄧肯 （4星）</option>";
echo "<option value=\"12\"";
if($id == 12) echo "selected=\"selected\"";
echo ">No.12 - 森林王者鄧肯 （5星）</option>";
echo "<option value=\"13\"";
if($id == 13) echo "selected=\"selected\"";
echo ">No.13 - 男爵奈寶尼 （2星）</option>";
echo "<option value=\"14\"";
if($id == 14) echo "selected=\"selected\"";
echo ">No.14 - 子爵奈寶尼 （3星）</option>";
echo "<option value=\"15\"";
if($id == 15) echo "selected=\"selected\"";
echo ">No.15 - 伯爵奈寶尼 （4星）</option>";
echo "<option value=\"16\"";
if($id == 16) echo "selected=\"selected\"";
echo ">No.16 - 侯爵奈寶尼 （5星）</option>";
echo "<option value=\"17\"";
if($id == 17) echo "selected=\"selected\"";
echo ">No.17 - 暗修導士安多 （2星）</option>";
echo "<option value=\"18\"";
if($id == 18) echo "selected=\"selected\"";
echo ">No.18 - 高級暗修導士安多 （3星）</option>";
echo "<option value=\"19\"";
if($id == 19) echo "selected=\"selected\"";
echo ">No.19 - 死靈術士安多 （4星）</option>";
echo "<option value=\"20\"";
if($id == 20) echo "selected=\"selected\"";
echo ">No.20 - 死靈祭師安多 （5星）</option>";
echo "<option value=\"21\"";
if($id == 21) echo "selected=\"selected\"";
echo ">No.21 - 水方士 （2星）</option>";
echo "<option value=\"22\"";
if($id == 22) echo "selected=\"selected\"";
echo ">No.22 - 清川真人 （3星）</option>";
echo "<option value=\"23\"";
if($id == 23) echo "selected=\"selected\"";
echo ">No.23 - 靈江仙人 （4星）</option>";
echo "<option value=\"24\"";
if($id == 24) echo "selected=\"selected\"";
echo ">No.24 - 青龍孟章神君 （5星）</option>";
echo "<option value=\"25\"";
if($id == 25) echo "selected=\"selected\"";
echo ">No.25 - 火方士 （2星）</option>";
echo "<option value=\"26\"";
if($id == 26) echo "selected=\"selected\"";
echo ">No.26 - 赤灶真人 （3星）</option>";
echo "<option value=\"27\"";
if($id == 27) echo "selected=\"selected\"";
echo ">No.27 - 真火仙人 （4星）</option>";
echo "<option value=\"28\"";
if($id == 28) echo "selected=\"selected\"";
echo ">No.28 - 朱雀陵光神君 （5星）</option>";
echo "<option value=\"29\"";
if($id == 29) echo "selected=\"selected\"";
echo ">No.29 - 木方士 （2星）</option>";
echo "<option value=\"30\"";
if($id == 30) echo "selected=\"selected\"";
echo ">No.30 - 九地真人 （3星）</option>";
echo "<option value=\"31\"";
if($id == 31) echo "selected=\"selected\"";
echo ">No.31 - 虛土仙人 （4星）</option>";
echo "<option value=\"32\"";
if($id == 32) echo "selected=\"selected\"";
echo ">No.32 - 玄武執明神君 （5星）</option>";
echo "<option value=\"33\"";
if($id == 33) echo "selected=\"selected\"";
echo ">No.33 - 陽方士 （2星）</option>";
echo "<option value=\"34\"";
if($id == 34) echo "selected=\"selected\"";
echo ">No.34 - 聖明真人 （3星）</option>";
echo "<option value=\"35\"";
if($id == 35) echo "selected=\"selected\"";
echo ">No.35 - 耀尊仙人 （4星）</option>";
echo "<option value=\"36\"";
if($id == 36) echo "selected=\"selected\"";
echo ">No.36 - 白虎監兵神君 （5星）</option>";
echo "<option value=\"37\"";
if($id == 37) echo "selected=\"selected\"";
echo ">No.37 - 陰方士 （2星）</option>";
echo "<option value=\"38\"";
if($id == 38) echo "selected=\"selected\"";
echo ">No.38 - 幽陵真人 （3星）</option>";
echo "<option value=\"39\"";
if($id == 39) echo "selected=\"selected\"";
echo ">No.39 - 紫微妖仙 （4星）</option>";
echo "<option value=\"40\"";
if($id == 40) echo "selected=\"selected\"";
echo ">No.40 - 饕餮渾沌魔君 （5星）</option>";
echo "<option value=\"41\"";
if($id == 41) echo "selected=\"selected\"";
echo ">No.41 - 冰花龍 （3星）</option>";
echo "<option value=\"42\"";
if($id == 42) echo "selected=\"selected\"";
echo ">No.42 - 冰晶龍 （4星）</option>";
echo "<option value=\"43\"";
if($id == 43) echo "selected=\"selected\"";
echo ">No.43 - 冰晶龍王 （5星）</option>";
echo "<option value=\"44\"";
if($id == 44) echo "selected=\"selected\"";
echo ">No.44 - 洋燭龍 （3星）</option>";
echo "<option value=\"45\"";
if($id == 45) echo "selected=\"selected\"";
echo ">No.45 - 星火龍 （4星）</option>";
echo "<option value=\"46\"";
if($id == 46) echo "selected=\"selected\"";
echo ">No.46 - 硝鐵火龍 （5星）</option>";
echo "<option value=\"47\"";
if($id == 47) echo "selected=\"selected\"";
echo ">No.47 - 碧甲龍 （3星）</option>";
echo "<option value=\"48\"";
if($id == 48) echo "selected=\"selected\"";
echo ">No.48 - 碧甲巖龍 （4星）</option>";
echo "<option value=\"49\"";
if($id == 49) echo "selected=\"selected\"";
echo ">No.49 - 靈山龍龜 （5星）</option>";
echo "<option value=\"50\"";
if($id == 50) echo "selected=\"selected\"";
echo ">No.50 - 光輝龍 （3星）</option>";
echo "<option value=\"51\"";
if($id == 51) echo "selected=\"selected\"";
echo ">No.51 - 閃耀龍 （4星）</option>";
echo "<option value=\"52\"";
if($id == 52) echo "selected=\"selected\"";
echo ">No.52 - 聖衡機龍 （5星）</option>";
echo "<option value=\"53\"";
if($id == 53) echo "selected=\"selected\"";
echo ">No.53 - 無頭龍 （3星）</option>";
echo "<option value=\"54\"";
if($id == 54) echo "selected=\"selected\"";
echo ">No.54 - 斷頭龍 （4星）</option>";
echo "<option value=\"55\"";
if($id == 55) echo "selected=\"selected\"";
echo ">No.55 - 魂索邪龍 （5星）</option>";
echo "<option value=\"56\"";
if($id == 56) echo "selected=\"selected\"";
echo ">No.56 - 冰原地精 （2星）</option>";
echo "<option value=\"57\"";
if($id == 57) echo "selected=\"selected\"";
echo ">No.57 - 淵寒大地精 （3星）</option>";
echo "<option value=\"58\"";
if($id == 58) echo "selected=\"selected\"";
echo ">No.58 - 火山地精 （2星）</option>";
echo "<option value=\"59\"";
if($id == 59) echo "selected=\"selected\"";
echo ">No.59 - 熾岩大地精 （3星）</option>";
echo "<option value=\"60\"";
if($id == 60) echo "selected=\"selected\"";
echo ">No.60 - 森林地精 （2星）</option>";
echo "<option value=\"61\"";
if($id == 61) echo "selected=\"selected\"";
echo ">No.61 - 碧石大地精 （3星）</option>";
echo "<option value=\"62\"";
if($id == 62) echo "selected=\"selected\"";
echo ">No.62 - 光明地精 （2星）</option>";
echo "<option value=\"63\"";
if($id == 63) echo "selected=\"selected\"";
echo ">No.63 - 輝芒大地精 （3星）</option>";
echo "<option value=\"64\"";
if($id == 64) echo "selected=\"selected\"";
echo ">No.64 - 黑暗地精 （2星）</option>";
echo "<option value=\"65\"";
if($id == 65) echo "selected=\"selected\"";
echo ">No.65 - 冥土大地精 （3星）</option>";
echo "<option value=\"66\"";
if($id == 66) echo "selected=\"selected\"";
echo ">No.66 - 海精靈 （2星）</option>";
echo "<option value=\"67\"";
if($id == 67) echo "selected=\"selected\"";
echo ">No.67 - 海躍精靈 （3星）</option>";
echo "<option value=\"68\"";
if($id == 68) echo "selected=\"selected\"";
echo ">No.68 - 火精靈 （2星）</option>";
echo "<option value=\"69\"";
if($id == 69) echo "selected=\"selected\"";
echo ">No.69 - 火舞精靈 （3星）</option>";
echo "<option value=\"70\"";
if($id == 70) echo "selected=\"selected\"";
echo ">No.70 - 花精靈 （2星）</option>";
echo "<option value=\"71\"";
if($id == 71) echo "selected=\"selected\"";
echo ">No.71 - 花冠精靈 （3星）</option>";
echo "<option value=\"72\"";
if($id == 72) echo "selected=\"selected\"";
echo ">No.72 - 月精靈 （2星）</option>";
echo "<option value=\"73\"";
if($id == 73) echo "selected=\"selected\"";
echo ">No.73 - 月光精靈 （3星）</option>";
echo "<option value=\"74\"";
if($id == 74) echo "selected=\"selected\"";
echo ">No.74 - 夜精靈 （2星）</option>";
echo "<option value=\"75\"";
if($id == 75) echo "selected=\"selected\"";
echo ">No.75 - 夜迷精靈 （3星）</option>";
echo "<option value=\"76\"";
if($id == 76) echo "selected=\"selected\"";
echo ">No.76 - 冰蜥蝪戰士 （2星）</option>";
echo "<option value=\"77\"";
if($id == 77) echo "selected=\"selected\"";
echo ">No.77 - 冰河蜥蝪戰士 （3星）</option>";
echo "<option value=\"78\"";
if($id == 78) echo "selected=\"selected\"";
echo ">No.78 - 赤蜥蝪戰士 （2星）</option>";
echo "<option value=\"79\"";
if($id == 79) echo "selected=\"selected\"";
echo ">No.79 - 赤焰蜥蝪戰士 （3星）</option>";
echo "<option value=\"80\"";
if($id == 80) echo "selected=\"selected\"";
echo ">No.80 - 翠蜥蝪戰士 （2星）</option>";
echo "<option value=\"81\"";
if($id == 81) echo "selected=\"selected\"";
echo ">No.81 - 森林蜥蝪戰士 （3星）</option>";
echo "<option value=\"82\"";
if($id == 82) echo "selected=\"selected\"";
echo ">No.82 - 光蜥蝪戰士 （2星）</option>";
echo "<option value=\"83\"";
if($id == 83) echo "selected=\"selected\"";
echo ">No.83 - 金光蜥蝪戰士 （3星）</option>";
echo "<option value=\"84\"";
if($id == 84) echo "selected=\"selected\"";
echo ">No.84 - 暗蜥蝪戰士 （2星）</option>";
echo "<option value=\"85\"";
if($id == 85) echo "selected=\"selected\"";
echo ">No.85 - 漆黑蜥蝪戰士 （3星）</option>";
echo "<option value=\"86\"";
if($id == 86) echo "selected=\"selected\"";
echo ">No.86 - 小魔女愛莉絲 （2星）</option>";
echo "<option value=\"87\"";
if($id == 87) echo "selected=\"selected\"";
echo ">No.87 - 占星士愛莉絲 （3星）</option>";
echo "<option value=\"88\"";
if($id == 88) echo "selected=\"selected\"";
echo ">No.88 - 小魔女瑪莉曼 （2星）</option>";
echo "<option value=\"89\"";
if($id == 89) echo "selected=\"selected\"";
echo ">No.89 - 火巫女瑪莉曼 （3星）</option>";
echo "<option value=\"90\"";
if($id == 90) echo "selected=\"selected\"";
echo ">No.90 - 小魔女凱莉絲 （2星）</option>";
echo "<option value=\"91\"";
if($id == 91) echo "selected=\"selected\"";
echo ">No.91 - 修道者凱莉絲 （3星）</option>";
echo "<option value=\"92\"";
if($id == 92) echo "selected=\"selected\"";
echo ">No.92 - 小魔女安迪莉亞 （2星）</option>";
echo "<option value=\"93\"";
if($id == 93) echo "selected=\"selected\"";
echo ">No.93 - 傳教士安迪莉亞 （3星）</option>";
echo "<option value=\"94\"";
if($id == 94) echo "selected=\"selected\"";
echo ">No.94 - 小魔女莉莉絲 （2星）</option>";
echo "<option value=\"95\"";
if($id == 95) echo "selected=\"selected\"";
echo ">No.95 - 鍊金士莉莉絲 （3星）</option>";
echo "<option value=\"96\"";
if($id == 96) echo "selected=\"selected\"";
echo ">No.96 - 水史萊姆 （1星）</option>";
echo "<option value=\"97\"";
if($id == 97) echo "selected=\"selected\"";
echo ">No.97 - 液態史萊姆 （2星）</option>";
echo "<option value=\"98\"";
if($id == 98) echo "selected=\"selected\"";
echo ">No.98 - 火史萊姆 （1星）</option>";
echo "<option value=\"99\"";
if($id == 99) echo "selected=\"selected\"";
echo ">No.99 - 燃燒史萊姆 （2星）</option>";
echo "<option value=\"100\"";
if($id == 100) echo "selected=\"selected\"";
echo ">No.100 - 木史萊姆 （1星）</option>";
echo "<option value=\"101\"";
if($id == 101) echo "selected=\"selected\"";
echo ">No.101 - 翠綠史萊姆 （2星）</option>";
echo "<option value=\"102\"";
if($id == 102) echo "selected=\"selected\"";
echo ">No.102 - 光史萊姆 （1星）</option>";
echo "<option value=\"103\"";
if($id == 103) echo "selected=\"selected\"";
echo ">No.103 - 天使史萊姆 （2星）</option>";
echo "<option value=\"104\"";
if($id == 104) echo "selected=\"selected\"";
echo ">No.104 - 暗史萊姆 （1星）</option>";
echo "<option value=\"105\"";
if($id == 105) echo "selected=\"selected\"";
echo ">No.105 - 幽靈史萊姆 （2星）</option>";
echo "<option value=\"106\"";
if($id == 106) echo "selected=\"selected\"";
echo ">No.106 - 蒼幽狼 （2星）</option>";
echo "<option value=\"107\"";
if($id == 107) echo "selected=\"selected\"";
echo ">No.107 - 蒼幽狼人 （3星）</option>";
echo "<option value=\"108\"";
if($id == 108) echo "selected=\"selected\"";
echo ">No.108 - 赤幽狼 （2星）</option>";
echo "<option value=\"109\"";
if($id == 109) echo "selected=\"selected\"";
echo ">No.109 - 赤幽狼人 （3星）</option>";
echo "<option value=\"110\"";
if($id == 110) echo "selected=\"selected\"";
echo ">No.110 - 青幽狼 （2星）</option>";
echo "<option value=\"111\"";
if($id == 111) echo "selected=\"selected\"";
echo ">No.111 - 青幽狼人 （3星）</option>";
echo "<option value=\"112\"";
if($id == 112) echo "selected=\"selected\"";
echo ">No.112 - 白幽狼 （2星）</option>";
echo "<option value=\"113\"";
if($id == 113) echo "selected=\"selected\"";
echo ">No.113 - 白幽狼人 （3星）</option>";
echo "<option value=\"114\"";
if($id == 114) echo "selected=\"selected\"";
echo ">No.114 - 黑幽狼 （2星）</option>";
echo "<option value=\"115\"";
if($id == 115) echo "selected=\"selected\"";
echo ">No.115 - 黑幽狼人 （3星）</option>";
echo "<option value=\"116\"";
if($id == 116) echo "selected=\"selected\"";
echo ">No.116 - 烏爾德 （3星）</option>";
echo "<option value=\"117\"";
if($id == 117) echo "selected=\"selected\"";
echo ">No.117 - 過去之烏爾德 （4星）</option>";
echo "<option value=\"118\"";
if($id == 118) echo "selected=\"selected\"";
echo ">No.118 - 歷史之烏爾德 （5星）</option>";
echo "<option value=\"119\"";
if($id == 119) echo "selected=\"selected\"";
echo ">No.119 - 斯庫爾德 （3星）</option>";
echo "<option value=\"120\"";
if($id == 120) echo "selected=\"selected\"";
echo ">No.120 - 未來之斯庫爾德 （4星）</option>";
echo "<option value=\"121\"";
if($id == 121) echo "selected=\"selected\"";
echo ">No.121 - 無常之斯庫爾德 （5星）</option>";
echo "<option value=\"122\"";
if($id == 122) echo "selected=\"selected\"";
echo ">No.122 - 薇兒丹蒂 （3星）</option>";
echo "<option value=\"123\"";
if($id == 123) echo "selected=\"selected\"";
echo ">No.123 - 現在之薇兒丹蒂 （4星）</option>";
echo "<option value=\"124\"";
if($id == 124) echo "selected=\"selected\"";
echo ">No.124 - 命運之薇兒丹蒂 （5星）</option>";
echo "<option value=\"125\"";
if($id == 125) echo "selected=\"selected\"";
echo ">No.125 - 伊登 （3星）</option>";
echo "<option value=\"126\"";
if($id == 126) echo "selected=\"selected\"";
echo ">No.126 - 聖果之伊登 （4星）</option>";
echo "<option value=\"127\"";
if($id == 127) echo "selected=\"selected\"";
echo ">No.127 - 永生之伊登 （5星）</option>";
echo "<option value=\"128\"";
if($id == 128) echo "selected=\"selected\"";
echo ">No.128 - 英靈殿侍女 （3星）</option>";
echo "<option value=\"129\"";
if($id == 129) echo "selected=\"selected\"";
echo ">No.129 - 戰魂之瓦爾基麗 （4星）</option>";
echo "<option value=\"130\"";
if($id == 130) echo "selected=\"selected\"";
echo ">No.130 - 催魂之瓦爾基麗 （5星）</option>";
echo "<option value=\"131\"";
if($id == 131) echo "selected=\"selected\"";
echo ">No.131 - 水遊俠 （3星）</option>";
echo "<option value=\"132\"";
if($id == 132) echo "selected=\"selected\"";
echo ">No.132 - 水舞劍士 （4星）</option>";
echo "<option value=\"133\"";
if($id == 133) echo "selected=\"selected\"";
echo ">No.133 - 水舞劍神 （5星）</option>";
echo "<option value=\"134\"";
if($id == 134) echo "selected=\"selected\"";
echo ">No.134 - 火遊俠 （3星）</option>";
echo "<option value=\"135\"";
if($id == 135) echo "selected=\"selected\"";
echo ">No.135 - 火焰戰士 （4星）</option>";
echo "<option value=\"136\"";
if($id == 136) echo "selected=\"selected\"";
echo ">No.136 - 炎舞軍神 （5星）</option>";
echo "<option value=\"137\"";
if($id == 137) echo "selected=\"selected\"";
echo ">No.137 - 木遊俠 （3星）</option>";
echo "<option value=\"138\"";
if($id == 138) echo "selected=\"selected\"";
echo ">No.138 - 翠綠狙擊手 （4星）</option>";
echo "<option value=\"139\"";
if($id == 139) echo "selected=\"selected\"";
echo ">No.139 - 疾風神射手 （5星）</option>";
echo "<option value=\"140\"";
if($id == 140) echo "selected=\"selected\"";
echo ">No.140 - 光遊俠 （3星）</option>";
echo "<option value=\"141\"";
if($id == 141) echo "selected=\"selected\"";
echo ">No.141 - 聖光遊俠 （4星）</option>";
echo "<option value=\"142\"";
if($id == 142) echo "selected=\"selected\"";
echo ">No.142 - 萬劍遊俠 （5星）</option>";
echo "<option value=\"143\"";
if($id == 143) echo "selected=\"selected\"";
echo ">No.143 - 暗遊俠 （3星）</option>";
echo "<option value=\"144\"";
if($id == 144) echo "selected=\"selected\"";
echo ">No.144 - 暗夜刺客 （4星）</option>";
echo "<option value=\"145\"";
if($id == 145) echo "selected=\"selected\"";
echo ">No.145 - 暗影劍豪 （5星）</option>";
echo "<option value=\"146\"";
if($id == 146) echo "selected=\"selected\"";
echo ">No.146 - 冰耀巨像 （3星）</option>";
echo "<option value=\"147\"";
if($id == 147) echo "selected=\"selected\"";
echo ">No.147 - 冰耀巨像‧解放 （4星）</option>";
echo "<option value=\"148\"";
if($id == 148) echo "selected=\"selected\"";
echo ">No.148 - 冰耀巨鱷 （5星）</option>";
echo "<option value=\"149\"";
if($id == 149) echo "selected=\"selected\"";
echo ">No.149 - 烙紅巨像 （3星）</option>";
echo "<option value=\"150\"";
if($id == 150) echo "selected=\"selected\"";
echo ">No.150 - 烙紅巨像‧解放 （4星）</option>";
echo "<option value=\"151\"";
if($id == 151) echo "selected=\"selected\"";
echo ">No.151 - 烙紅龍蜥 （5星）</option>";
echo "<option value=\"152\"";
if($id == 152) echo "selected=\"selected\"";
echo ">No.152 - 碧青巨像 （3星）</option>";
echo "<option value=\"153\"";
if($id == 153) echo "selected=\"selected\"";
echo ">No.153 - 碧青巨像‧解放 （4星）</option>";
echo "<option value=\"154\"";
if($id == 154) echo "selected=\"selected\"";
echo ">No.154 - 碧青行者 （5星）</option>";
echo "<option value=\"155\"";
if($id == 155) echo "selected=\"selected\"";
echo ">No.155 - 聖靈巨像 （3星）</option>";
echo "<option value=\"156\"";
if($id == 156) echo "selected=\"selected\"";
echo ">No.156 - 聖靈巨像‧解放 （4星）</option>";
echo "<option value=\"157\"";
if($id == 157) echo "selected=\"selected\"";
echo ">No.157 - 聖靈怒獅 （5星）</option>";
echo "<option value=\"158\"";
if($id == 158) echo "selected=\"selected\"";
echo ">No.158 - 暗月巨像 （3星）</option>";
echo "<option value=\"159\"";
if($id == 159) echo "selected=\"selected\"";
echo ">No.159 - 暗月巨像‧解放 （4星）</option>";
echo "<option value=\"160\"";
if($id == 160) echo "selected=\"selected\"";
echo ">No.160 - 暗月夜龍 （5星）</option>";
echo "<option value=\"161\"";
if($id == 161) echo "selected=\"selected\"";
echo ">No.161 - 機械鯨鯊 （2星）</option>";
echo "<option value=\"162\"";
if($id == 162) echo "selected=\"selected\"";
echo ">No.162 - 強化機械鯨鯊 （3星）</option>";
echo "<option value=\"163\"";
if($id == 163) echo "selected=\"selected\"";
echo ">No.163 - 變異機械鯨鯊 （4星）</option>";
echo "<option value=\"164\"";
if($id == 164) echo "selected=\"selected\"";
echo ">No.164 - 機械獅子 （2星）</option>";
echo "<option value=\"165\"";
if($id == 165) echo "selected=\"selected\"";
echo ">No.165 - 強化機械獅子 （3星）</option>";
echo "<option value=\"166\"";
if($id == 166) echo "selected=\"selected\"";
echo ">No.166 - 狂暴機械獅子 （4星）</option>";
echo "<option value=\"167\"";
if($id == 167) echo "selected=\"selected\"";
echo ">No.167 - 機械犀牛 （2星）</option>";
echo "<option value=\"168\"";
if($id == 168) echo "selected=\"selected\"";
echo ">No.168 - 強化機械犀牛 （3星）</option>";
echo "<option value=\"169\"";
if($id == 169) echo "selected=\"selected\"";
echo ">No.169 - 野蠻機械犀牛 （4星）</option>";
echo "<option value=\"170\"";
if($id == 170) echo "selected=\"selected\"";
echo ">No.170 - 機械狼 （2星）</option>";
echo "<option value=\"171\"";
if($id == 171) echo "selected=\"selected\"";
echo ">No.171 - 強化機械狼 （3星）</option>";
echo "<option value=\"172\"";
if($id == 172) echo "selected=\"selected\"";
echo ">No.172 - 重甲機械狼 （4星）</option>";
echo "<option value=\"173\"";
if($id == 173) echo "selected=\"selected\"";
echo ">No.173 - 機械豹 （2星）</option>";
echo "<option value=\"174\"";
if($id == 174) echo "selected=\"selected\"";
echo ">No.174 - 強化機械豹 （3星）</option>";
echo "<option value=\"175\"";
if($id == 175) echo "selected=\"selected\"";
echo ">No.175 - 掠奪機械豹 （4星）</option>";
echo "<option value=\"176\"";
if($id == 176) echo "selected=\"selected\"";
echo ">No.176 - 海獸 （3星）</option>";
echo "<option value=\"177\"";
if($id == 177) echo "selected=\"selected\"";
echo ">No.177 - 克蘇魯 （4星）</option>";
echo "<option value=\"178\"";
if($id == 178) echo "selected=\"selected\"";
echo ">No.178 - 邪神克蘇魯 （5星）</option>";
echo "<option value=\"179\"";
if($id == 179) echo "selected=\"selected\"";
echo ">No.179 - 地獄三頭犬 （3星）</option>";
echo "<option value=\"180\"";
if($id == 180) echo "selected=\"selected\"";
echo ">No.180 - 基路比魯斯 （4星）</option>";
echo "<option value=\"181\"";
if($id == 181) echo "selected=\"selected\"";
echo ">No.181 - 冥府兇獸基路比魯斯 （5星）</option>";
echo "<option value=\"182\"";
if($id == 182) echo "selected=\"selected\"";
echo ">No.182 - 蛇妖 （3星）</option>";
echo "<option value=\"183\"";
if($id == 183) echo "selected=\"selected\"";
echo ">No.183 - 美杜莎 （4星）</option>";
echo "<option value=\"184\"";
if($id == 184) echo "selected=\"selected\"";
echo ">No.184 - 妖女美杜莎 （5星）</option>";
echo "<option value=\"185\"";
if($id == 185) echo "selected=\"selected\"";
echo ">No.185 - 鷹頭獸 （3星）</option>";
echo "<option value=\"186\"";
if($id == 186) echo "selected=\"selected\"";
echo ">No.186 - 獅鷲 （4星）</option>";
echo "<option value=\"187\"";
if($id == 187) echo "selected=\"selected\"";
echo ">No.187 - 獅鷲獸王 （5星）</option>";
echo "<option value=\"188\"";
if($id == 188) echo "selected=\"selected\"";
echo ">No.188 - 魔羊 （3星）</option>";
echo "<option value=\"189\"";
if($id == 189) echo "selected=\"selected\"";
echo ">No.189 - 魔羊怪 （4星）</option>";
echo "<option value=\"190\"";
if($id == 190) echo "selected=\"selected\"";
echo ">No.190 - 惡魔巴風特 （5星）</option>";
echo "<option value=\"191\"";
if($id == 191) echo "selected=\"selected\"";
echo ">No.191 - 波塞頓 （5星）</option>";
echo "<option value=\"192\"";
if($id == 192) echo "selected=\"selected\"";
echo ">No.192 - 海神波塞頓 （6星）</option>";
echo "<option value=\"193\"";
if($id == 193) echo "selected=\"selected\"";
echo ">No.193 - 赫淮斯托斯 （5星）</option>";
echo "<option value=\"194\"";
if($id == 194) echo "selected=\"selected\"";
echo ">No.194 - 奧林火神赫淮斯托斯 （6星）</option>";
echo "<option value=\"195\"";
if($id == 195) echo "selected=\"selected\"";
echo ">No.195 - 雅典娜 （5星）</option>";
echo "<option value=\"196\"";
if($id == 196) echo "selected=\"selected\"";
echo ">No.196 - 智慧女神雅典娜 （6星）</option>";
echo "<option value=\"197\"";
if($id == 197) echo "selected=\"selected\"";
echo ">No.197 - 阿波羅 （5星）</option>";
echo "<option value=\"198\"";
if($id == 198) echo "selected=\"selected\"";
echo ">No.198 - 光明之神阿波羅 （6星）</option>";
echo "<option value=\"199\"";
if($id == 199) echo "selected=\"selected\"";
echo ">No.199 - 阿提密斯 （5星）</option>";
echo "<option value=\"200\"";
if($id == 200) echo "selected=\"selected\"";
echo ">No.200 - 月之狩獵女神阿提密斯 （6星）</option>";
echo "<option value=\"201\"";
if($id == 201) echo "selected=\"selected\"";
echo ">No.201 - 費雷 （5星）</option>";
echo "<option value=\"202\"";
if($id == 202) echo "selected=\"selected\"";
echo ">No.202 - 勝利海神費雷 （6星）</option>";
echo "<option value=\"203\"";
if($id == 203) echo "selected=\"selected\"";
echo ">No.203 - 提爾 （5星）</option>";
echo "<option value=\"204\"";
if($id == 204) echo "selected=\"selected\"";
echo ">No.204 - 獨臂戰神提爾 （6星）</option>";
echo "<option value=\"205\"";
if($id == 205) echo "selected=\"selected\"";
echo ">No.205 - 費蕾雅 （5星）</option>";
echo "<option value=\"206\"";
if($id == 206) echo "selected=\"selected\"";
echo ">No.206 - 妙曼愛神費蕾雅 （6星）</option>";
echo "<option value=\"207\"";
if($id == 207) echo "selected=\"selected\"";
echo ">No.207 - 索爾 （5星）</option>";
echo "<option value=\"208\"";
if($id == 208) echo "selected=\"selected\"";
echo ">No.208 - 轟天雷神索爾 （6星）</option>";
echo "<option value=\"209\"";
if($id == 209) echo "selected=\"selected\"";
echo ">No.209 - 洛基 （5星）</option>";
echo "<option value=\"210\"";
if($id == 210) echo "selected=\"selected\"";
echo ">No.210 - 黃昏號角洛基 （6星）</option>";
echo "<option value=\"211\"";
if($id == 211) echo "selected=\"selected\"";
echo ">No.211 - 泰芙努特 （5星）</option>";
echo "<option value=\"212\"";
if($id == 212) echo "selected=\"selected\"";
echo ">No.212 - 雨神泰芙努特 （6星）</option>";
echo "<option value=\"213\"";
if($id == 213) echo "selected=\"selected\"";
echo ">No.213 - 賽特 （5星）</option>";
echo "<option value=\"214\"";
if($id == 214) echo "selected=\"selected\"";
echo ">No.214 - 戰爭之神賽特 （6星）</option>";
echo "<option value=\"215\"";
if($id == 215) echo "selected=\"selected\"";
echo ">No.215 - 舒 （5星）</option>";
echo "<option value=\"216\"";
if($id == 216) echo "selected=\"selected\"";
echo ">No.216 - 天空之神‧舒 （6星）</option>";
echo "<option value=\"217\"";
if($id == 217) echo "selected=\"selected\"";
echo ">No.217 - 拉 （5星）</option>";
echo "<option value=\"218\"";
if($id == 218) echo "selected=\"selected\"";
echo ">No.218 - 太陽之子拉 （6星）</option>";
echo "<option value=\"219\"";
if($id == 219) echo "selected=\"selected\"";
echo ">No.219 - 奧西利斯 （5星）</option>";
echo "<option value=\"220\"";
if($id == 220) echo "selected=\"selected\"";
echo ">No.220 - 不死冥王奧西利斯 （6星）</option>";
echo "<option value=\"221\"";
if($id == 221) echo "selected=\"selected\"";
echo ">No.221 - 海龍 （5星）</option>";
echo "<option value=\"222\"";
if($id == 222) echo "selected=\"selected\"";
echo ">No.222 - 東海龍王‧敖廣 （6星）</option>";
echo "<option value=\"223\"";
if($id == 223) echo "selected=\"selected\"";
echo ">No.223 - 蓮藕仔 （5星）</option>";
echo "<option value=\"224\"";
if($id == 224) echo "selected=\"selected\"";
echo ">No.224 - 三太子‧哪吒 （6星）</option>";
echo "<option value=\"225\"";
if($id == 225) echo "selected=\"selected\"";
echo ">No.225 - 大力王 （5星）</option>";
echo "<option value=\"226\"";
if($id == 226) echo "selected=\"selected\"";
echo ">No.226 - 平天大聖‧牛魔王 （6星）</option>";
echo "<option value=\"227\"";
if($id == 227) echo "selected=\"selected\"";
echo ">No.227 - 美猴王 （5星）</option>";
echo "<option value=\"228\"";
if($id == 228) echo "selected=\"selected\"";
echo ">No.228 - 齊天大聖‧孫悟空 （6星）</option>";
echo "<option value=\"229\"";
if($id == 229) echo "selected=\"selected\"";
echo ">No.229 - 妖狐 （5星）</option>";
echo "<option value=\"230\"";
if($id == 230) echo "selected=\"selected\"";
echo ">No.230 - 白臉金毛‧妲己 （6星）</option>";
echo "<option value=\"231\"";
if($id == 231) echo "selected=\"selected\"";
echo ">No.231 - 機械水龍 （5星）</option>";
echo "<option value=\"232\"";
if($id == 232) echo "selected=\"selected\"";
echo ">No.232 - 機械水神龍‧內拉羅斯 （6星）</option>";
echo "<option value=\"233\"";
if($id == 233) echo "selected=\"selected\"";
echo ">No.233 - 機械火龍 （5星）</option>";
echo "<option value=\"234\"";
if($id == 234) echo "selected=\"selected\"";
echo ">No.234 - 機械火神龍‧伊索爾德 （6星）</option>";
echo "<option value=\"235\"";
if($id == 235) echo "selected=\"selected\"";
echo ">No.235 - 機械地龍 （5星）</option>";
echo "<option value=\"236\"";
if($id == 236) echo "selected=\"selected\"";
echo ">No.236 - 機械地神龍‧卡斯迪 （6星）</option>";
echo "<option value=\"237\"";
if($id == 237) echo "selected=\"selected\"";
echo ">No.237 - 機械聖龍 （5星）</option>";
echo "<option value=\"238\"";
if($id == 238) echo "selected=\"selected\"";
echo ">No.238 - 機械聖皇龍‧泰瑞那斯 （6星）</option>";
echo "<option value=\"239\"";
if($id == 239) echo "selected=\"selected\"";
echo ">No.239 - 機械闍龍 （5星）</option>";
echo "<option value=\"240\"";
if($id == 240) echo "selected=\"selected\"";
echo ">No.240 - 機械冥王龍‧萊瑞姆 （6星）</option>";
echo "<option value=\"241\"";
if($id == 241) echo "selected=\"selected\"";
echo ">No.241 - 破碎之蒼魂 （1星）</option>";
echo "<option value=\"242\"";
if($id == 242) echo "selected=\"selected\"";
echo ">No.242 - 破碎之赤魂 （1星）</option>";
echo "<option value=\"243\"";
if($id == 243) echo "selected=\"selected\"";
echo ">No.243 - 破碎之青魂 （1星）</option>";
echo "<option value=\"244\"";
if($id == 244) echo "selected=\"selected\"";
echo ">No.244 - 破碎之白魂 （1星）</option>";
echo "<option value=\"245\"";
if($id == 245) echo "selected=\"selected\"";
echo ">No.245 - 破碎之黑魂 （1星）</option>";
echo "<option value=\"246\"";
if($id == 246) echo "selected=\"selected\"";
echo ">No.246 - 重生之蒼魂 （2星）</option>";
echo "<option value=\"247\"";
if($id == 247) echo "selected=\"selected\"";
echo ">No.247 - 重生之赤魂 （2星）</option>";
echo "<option value=\"248\"";
if($id == 248) echo "selected=\"selected\"";
echo ">No.248 - 重生之青魂 （2星）</option>";
echo "<option value=\"249\"";
if($id == 249) echo "selected=\"selected\"";
echo ">No.249 - 重生之白魂 （2星）</option>";
echo "<option value=\"250\"";
if($id == 250) echo "selected=\"selected\"";
echo ">No.250 - 重生之黑魂 （2星）</option>";
echo "<option value=\"251\"";
if($id == 251) echo "selected=\"selected\"";
echo ">No.251 - 共生之蒼魂 （3星）</option>";
echo "<option value=\"252\"";
if($id == 252) echo "selected=\"selected\"";
echo ">No.252 - 共生之赤魂 （3星）</option>";
echo "<option value=\"253\"";
if($id == 253) echo "selected=\"selected\"";
echo ">No.253 - 共生之青魂 （3星）</option>";
echo "<option value=\"254\"";
if($id == 254) echo "selected=\"selected\"";
echo ">No.254 - 共生之白魂 （3星）</option>";
echo "<option value=\"255\"";
if($id == 255) echo "selected=\"selected\"";
echo ">No.255 - 共生之黑魂 （3星）</option>";
echo "<option value=\"256\"";
if($id == 256) echo "selected=\"selected\"";
echo ">No.256 - 永恆之蒼魂 （4星）</option>";
echo "<option value=\"257\"";
if($id == 257) echo "selected=\"selected\"";
echo ">No.257 - 永恆之赤魂 （4星）</option>";
echo "<option value=\"258\"";
if($id == 258) echo "selected=\"selected\"";
echo ">No.258 - 永恆之青魂 （4星）</option>";
echo "<option value=\"259\"";
if($id == 259) echo "selected=\"selected\"";
echo ">No.259 - 永恆之白魂 （4星）</option>";
echo "<option value=\"260\"";
if($id == 260) echo "selected=\"selected\"";
echo ">No.260 - 永恆之黑魂 （4星）</option>";
echo "<option value=\"261\"";
if($id == 261) echo "selected=\"selected\"";
echo ">No.261 - 水晶龍蛋 （1星）</option>";
echo "<option value=\"262\"";
if($id == 262) echo "selected=\"selected\"";
echo ">No.262 - 破殼水晶龍 （3星）</option>";
echo "<option value=\"263\"";
if($id == 263) echo "selected=\"selected\"";
echo ">No.263 - 稀有水晶龍 （5星）</option>";
echo "<option value=\"264\"";
if($id == 264) echo "selected=\"selected\"";
echo ">No.264 - 詛咒之劍 （1星）</option>";
echo "<option value=\"265\"";
if($id == 265) echo "selected=\"selected\"";
echo ">No.265 - 殺戮之劍 （3星）</option>";
echo "<option value=\"266\"";
if($id == 266) echo "selected=\"selected\"";
echo ">No.266 - 魔神之劍 （5星）</option>";
echo "<option value=\"267\"";
if($id == 267) echo "selected=\"selected\"";
echo ">No.267 - 蜜涎獸 （1星）</option>";
echo "<option value=\"268\"";
if($id == 268) echo "selected=\"selected\"";
echo ">No.268 - 蜜羽獸 （3星）</option>";
echo "<option value=\"269\"";
if($id == 269) echo "selected=\"selected\"";
echo ">No.269 - 蜜月獸 （5星）</option>";
echo "<option value=\"270\"";
if($id == 270) echo "selected=\"selected\"";
echo ">No.270 - 海洋小靈魂石 （1星）</option>";
echo "<option value=\"271\"";
if($id == 271) echo "selected=\"selected\"";
echo ">No.271 - 火焰小靈魂石 （1星）</option>";
echo "<option value=\"272\"";
if($id == 272) echo "selected=\"selected\"";
echo ">No.272 - 大地小靈魂石 （1星）</option>";
echo "<option value=\"273\"";
if($id == 273) echo "selected=\"selected\"";
echo ">No.273 - 神聖小靈魂石 （1星）</option>";
echo "<option value=\"274\"";
if($id == 274) echo "selected=\"selected\"";
echo ">No.274 - 鬼魅小靈魂石 （1星）</option>";
echo "<option value=\"275\"";
if($id == 275) echo "selected=\"selected\"";
echo ">No.275 - 海洋靈魂石 （2星）</option>";
echo "<option value=\"276\"";
if($id == 276) echo "selected=\"selected\"";
echo ">No.276 - 火焰靈魂石 （2星）</option>";
echo "<option value=\"277\"";
if($id == 277) echo "selected=\"selected\"";
echo ">No.277 - 大地靈魂石 （2星）</option>";
echo "<option value=\"278\"";
if($id == 278) echo "selected=\"selected\"";
echo ">No.278 - 神聖靈魂石 （2星）</option>";
echo "<option value=\"279\"";
if($id == 279) echo "selected=\"selected\"";
echo ">No.279 - 鬼魅靈魂石 （2星）</option>";
echo "<option value=\"280\"";
if($id == 280) echo "selected=\"selected\"";
echo ">No.280 - 海洋千年靈魂石 （3星）</option>";
echo "<option value=\"281\"";
if($id == 281) echo "selected=\"selected\"";
echo ">No.281 - 火焰千年靈魂石 （3星）</option>";
echo "<option value=\"282\"";
if($id == 282) echo "selected=\"selected\"";
echo ">No.282 - 大地千年靈魂石 （3星）</option>";
echo "<option value=\"283\"";
if($id == 283) echo "selected=\"selected\"";
echo ">No.283 - 神聖千年靈魂石 （3星）</option>";
echo "<option value=\"284\"";
if($id == 284) echo "selected=\"selected\"";
echo ">No.284 - 鬼魅千年靈魂石 （3星）</option>";
echo "<option value=\"285\"";
if($id == 285) echo "selected=\"selected\"";
echo ">No.285 - 元素操縱者 - 迪亞布羅 （7星）</option>";
echo "<option value=\"286\"";
if($id == 286) echo "selected=\"selected\"";
echo ">No.286 - 萬魔之王 - 薩魯曼 （7星）</option>";
echo "<option value=\"287\"";
if($id == 287) echo "selected=\"selected\"";
echo ">No.287 - 碑紋騎士 - 奧丁 （7星）</option>";
echo "<option value=\"288\"";
if($id == 288) echo "selected=\"selected\"";
echo ">No.288 - 雙體共生 - 噬日狼 （7星）</option>";
echo "<option value=\"289\"";
if($id == 289) echo "selected=\"selected\"";
echo ">No.289 - 雙體共生 - 喰月狼 （7星）</option>";
echo "<option value=\"290\"";
if($id == 290) echo "selected=\"selected\"";
echo ">No.290 - 雖死猶在 - 毒龍尼德霍格 （7星）</option>";
echo "<option value=\"291\"";
if($id == 291) echo "selected=\"selected\"";
echo ">No.291 - 鬼魅萬年靈魂石 （6星）</option>";
echo "<option value=\"292\"";
if($id == 292) echo "selected=\"selected\"";
echo ">No.292 - 人面怪鳥 （6星）</option>";
echo "<option value=\"293\"";
if($id == 293) echo "selected=\"selected\"";
echo ">No.293 - 米迦勒‧路西法 （6星）</option>";
echo "<option value=\"294\"";
if($id == 294) echo "selected=\"selected\"";
echo ">No.294 - 通透的蛋 （3星）</option>";
echo "<option value=\"295\"";
if($id == 295) echo "selected=\"selected\"";
echo ">No.295 - 海拉 （4星）</option>";
echo "<option value=\"296\"";
if($id == 296) echo "selected=\"selected\"";
echo ">No.296 - 幻夢魚仙‧伊德海拉 （5星）</option>";
echo "<option value=\"297\"";
if($id == 297) echo "selected=\"selected\"";
echo ">No.297 - 火紅的蛋 （3星）</option>";
echo "<option value=\"298\"";
if($id == 298) echo "selected=\"selected\"";
echo ">No.298 - 梅格 （4星）</option>";
echo "<option value=\"299\"";
if($id == 299) echo "selected=\"selected\"";
echo ">No.299 - 龍裔‧梅格籣斯 （5星）</option>";
echo "<option value=\"300\"";
if($id == 300) echo "selected=\"selected\"";
echo ">No.300 - 翠綠的蛋 （3星）</option>";
echo "<option value=\"301\"";
if($id == 301) echo "selected=\"selected\"";
echo ">No.301 - 伊薇特 （4星）</option>";
echo "<option value=\"302\"";
if($id == 302) echo "selected=\"selected\"";
echo ">No.302 - 蝶妖伊薇特 （5星）</option>";
echo "<option value=\"303\"";
if($id == 303) echo "selected=\"selected\"";
echo ">No.303 - 閃亮的蛋 （3星）</option>";
echo "<option value=\"304\"";
if($id == 304) echo "selected=\"selected\"";
echo ">No.304 - 瑪格 （4星）</option>";
echo "<option value=\"305\"";
if($id == 305) echo "selected=\"selected\"";
echo ">No.305 - 聖蜂后‧瑪格莉特 （5星）</option>";
echo "<option value=\"306\"";
if($id == 306) echo "selected=\"selected\"";
echo ">No.306 - 暗啞的蛋 （3星）</option>";
echo "<option value=\"307\"";
if($id == 307) echo "selected=\"selected\"";
echo ">No.307 - 伊莎貝爾 （4星）</option>";
echo "<option value=\"308\"";
if($id == 308) echo "selected=\"selected\"";
echo ">No.308 - 黑寡婦伊莎貝爾 （5星）</option>";
echo "<option value=\"309\"";
if($id == 309) echo "selected=\"selected\"";
echo ">No.309 - 水之異界龍 （4星）</option>";
echo "<option value=\"310\"";
if($id == 310) echo "selected=\"selected\"";
echo ">No.310 - 深潛者之父‧達貢 （5星）</option>";
echo "<option value=\"311\"";
if($id == 311) echo "selected=\"selected\"";
echo ">No.311 - 火之異界龍 （4星）</option>";
echo "<option value=\"312\"";
if($id == 312) echo "selected=\"selected\"";
echo ">No.312 - 火焰共生者‧克圖格亞 （5星）</option>";
echo "<option value=\"313\"";
if($id == 313) echo "selected=\"selected\"";
echo ">No.313 - 風之異界龍 （4星）</option>";
echo "<option value=\"314\"";
if($id == 314) echo "selected=\"selected\"";
echo ">No.314 - 不朽尖吼者‧拜亞基 （5星）</option>";
echo "<option value=\"315\"";
if($id == 315) echo "selected=\"selected\"";
echo ">No.315 - 光之異界龍 （4星）</option>";
echo "<option value=\"316\"";
if($id == 316) echo "selected=\"selected\"";
echo ">No.316 - 招蕩的輝芒‧圖爾茲查 （5星）</option>";
echo "<option value=\"317\"";
if($id == 317) echo "selected=\"selected\"";
echo ">No.317 - 暗之異界龍 （4星）</option>";
echo "<option value=\"318\"";
if($id == 318) echo "selected=\"selected\"";
echo ">No.318 - 群山中之恐怖‧法格恩 （5星）</option>";
echo "<option value=\"319\"";
if($id == 319) echo "selected=\"selected\"";
echo ">No.319 - 破損的海神守護石像 （2星）</option>";
echo "<option value=\"320\"";
if($id == 320) echo "selected=\"selected\"";
echo ">No.320 - 海神守護石像 （3星）</option>";
echo "<option value=\"321\"";
if($id == 321) echo "selected=\"selected\"";
echo ">No.321 - 破損的火神守護石像 （2星）</option>";
echo "<option value=\"322\"";
if($id == 322) echo "selected=\"selected\"";
echo ">No.322 - 火神守護石像 （3星）</option>";
echo "<option value=\"323\"";
if($id == 323) echo "selected=\"selected\"";
echo ">No.323 - 破損的女戰神守護石像 （2星）</option>";
echo "<option value=\"324\"";
if($id == 324) echo "selected=\"selected\"";
echo ">No.324 - 女戰神守護石像 （3星）</option>";
echo "<option value=\"325\"";
if($id == 325) echo "selected=\"selected\"";
echo ">No.325 - 破損的太陽神守護石像 （2星）</option>";
echo "<option value=\"326\"";
if($id == 326) echo "selected=\"selected\"";
echo ">No.326 - 太陽神守護石像 （3星）</option>";
echo "<option value=\"327\"";
if($id == 327) echo "selected=\"selected\"";
echo ">No.327 - 破損的月神守護石像 （2星）</option>";
echo "<option value=\"328\"";
if($id == 328) echo "selected=\"selected\"";
echo ">No.328 - 月神守護石像 （3星）</option>";
echo "<option value=\"329\"";
if($id == 329) echo "selected=\"selected\"";
echo ">No.329 - 浪濤史萊姆 （4星）</option>";
echo "<option value=\"330\"";
if($id == 330) echo "selected=\"selected\"";
echo ">No.330 - 烈炎史萊姆 （4星）</option>";
echo "<option value=\"331\"";
if($id == 331) echo "selected=\"selected\"";
echo ">No.331 - 花豔史萊姆 （4星）</option>";
echo "<option value=\"332\"";
if($id == 332) echo "selected=\"selected\"";
echo ">No.332 - 神聖史萊姆 （4星）</option>";
echo "<option value=\"333\"";
if($id == 333) echo "selected=\"selected\"";
echo ">No.333 - 邪魔史萊姆 （4星）</option>";
echo "<option value=\"334\"";
if($id == 334) echo "selected=\"selected\"";
echo ">No.334 - 海韻女皇 （4星）</option>";
echo "<option value=\"335\"";
if($id == 335) echo "selected=\"selected\"";
echo ">No.335 - 火岩領主 （4星）</option>";
echo "<option value=\"336\"";
if($id == 336) echo "selected=\"selected\"";
echo ">No.336 - 花冠貴婦 （4星）</option>";
echo "<option value=\"337\"";
if($id == 337) echo "selected=\"selected\"";
echo ">No.337 - 月耀公主 （4星）</option>";
echo "<option value=\"338\"";
if($id == 338) echo "selected=\"selected\"";
echo ">No.338 - 夜影魔女 （4星）</option>";
echo "<option value=\"339\"";
if($id == 339) echo "selected=\"selected\"";
echo ">No.339 - 冰谷蜥蜴騎士 （4星）</option>";
echo "<option value=\"340\"";
if($id == 340) echo "selected=\"selected\"";
echo ">No.340 - 岩漿蜥蜴騎士 （4星）</option>";
echo "<option value=\"341\"";
if($id == 341) echo "selected=\"selected\"";
echo ">No.341 - 密林蜥蜴騎士 （4星）</option>";
echo "<option value=\"342\"";
if($id == 342) echo "selected=\"selected\"";
echo ">No.342 - 聖光蜥蜴騎士 （4星）</option>";
echo "<option value=\"343\"";
if($id == 343) echo "selected=\"selected\"";
echo ">No.343 - 黑雷蜥蜴騎士 （4星）</option>";
echo "<option value=\"344\"";
if($id == 344) echo "selected=\"selected\"";
echo ">No.344 - 特洛伊公主 （5星）</option>";
echo "<option value=\"345\"";
if($id == 345) echo "selected=\"selected\"";
echo ">No.345 - 受詛咒的先知‧卡珊德拉 （6星）</option>";
echo "<option value=\"346\"";
if($id == 346) echo "selected=\"selected\"";
echo ">No.346 - 科耳喀斯皇女 （5星）</option>";
echo "<option value=\"347\"";
if($id == 347) echo "selected=\"selected\"";
echo ">No.347 - 愛與恨的魔女‧美狄亞 （6星）</option>";
echo "<option value=\"348\"";
if($id == 348) echo "selected=\"selected\"";
echo ">No.348 - 薩爾瑪提亞女皇 （5星）</option>";
echo "<option value=\"349\"";
if($id == 349) echo "selected=\"selected\"";
echo ">No.349 - 黑魔法女巫‧喀耳刻 （6星）</option>";
echo "<option value=\"350\"";
if($id == 350) echo "selected=\"selected\"";
echo ">No.350 - 寒霧劍塚‧卡戎 （6星）</option>";
echo "<option value=\"351\"";
if($id == 351) echo "selected=\"selected\"";
echo ">No.351 - 機關傀儡‧紅月 （6星）</option>";
echo "<option value=\"352\"";
if($id == 352) echo "selected=\"selected\"";
echo ">No.352 - 腐林魔女‧布萊爾 （6星）</option>";
echo "<option value=\"353\"";
if($id == 353) echo "selected=\"selected\"";
echo ">No.353 - 鐵處女像‧浮士德 （6星）</option>";
echo "<option value=\"354\"";
if($id == 354) echo "selected=\"selected\"";
echo ">No.354 - 貓公爵‧費利克斯 （6星）</option>";
echo "<option value=\"355\"";
if($id == 355) echo "selected=\"selected\"";
echo ">No.355 - 持劍侍女‧波比 （5星）</option>";
echo "<option value=\"356\"";
if($id == 356) echo "selected=\"selected\"";
echo ">No.356 - 白羊宮‧波比 （6星）</option>";
echo "<option value=\"357\"";
if($id == 357) echo "selected=\"selected\"";
echo ">No.357 - 攻城者‧阿姆土唐 （5星）</option>";
echo "<option value=\"358\"";
if($id == 358) echo "selected=\"selected\"";
echo ">No.358 - 金牛宮‧阿姆土唐 （6星）</option>";
echo "<option value=\"359\"";
if($id == 359) echo "selected=\"selected\"";
echo ">No.359 - 雙劍士‧波魯克斯 （5星）</option>";
echo "<option value=\"360\"";
if($id == 360) echo "selected=\"selected\"";
echo ">No.360 - 雙子宮‧加斯陀與波魯克斯 （6星）</option>";
echo "<option value=\"361\"";
if($id == 361) echo "selected=\"selected\"";
echo ">No.361 - 暗影刺客‧約翰 （5星）</option>";
echo "<option value=\"362\"";
if($id == 362) echo "selected=\"selected\"";
echo ">No.362 - 巨蟹宮‧約翰 （6星）</option>";
echo "<option value=\"363\"";
if($id == 363) echo "selected=\"selected\"";
echo ">No.363 - 重劍士‧加里昂 （5星）</option>";
echo "<option value=\"364\"";
if($id == 364) echo "selected=\"selected\"";
echo ">No.364 - 獅子宮‧加里昂 （6星）</option>";
echo "<option value=\"365\"";
if($id == 365) echo "selected=\"selected\"";
echo ">No.365 - 割穗少女‧普西芬妮 （5星）</option>";
echo "<option value=\"366\"";
if($id == 366) echo "selected=\"selected\"";
echo ">No.366 - 處女宮‧普西芬妮 （6星）</option>";
echo "<option value=\"367\"";
if($id == 367) echo "selected=\"selected\"";
echo ">No.367 - 聖殿武士‧露娜 （5星）</option>";
echo "<option value=\"368\"";
if($id == 368) echo "selected=\"selected\"";
echo ">No.368 - 天秤宮‧露娜 （6星）</option>";
echo "<option value=\"369\"";
if($id == 369) echo "selected=\"selected\"";
echo ">No.369 - 重鐮刺客‧艾瑪 （5星）</option>";
echo "<option value=\"370\"";
if($id == 370) echo "selected=\"selected\"";
echo ">No.370 - 天蠍宮‧艾瑪 （6星）</option>";
echo "<option value=\"371\"";
if($id == 371) echo "selected=\"selected\"";
echo ">No.371 - 綠林行者‧赫茲 （5星）</option>";
echo "<option value=\"372\"";
if($id == 372) echo "selected=\"selected\"";
echo ">No.372 - 人馬宮‧赫茲 （6星）</option>";
echo "<option value=\"373\"";
if($id == 373) echo "selected=\"selected\"";
echo ">No.373 - 碎岩武者‧杜門 （5星）</option>";
echo "<option value=\"374\"";
if($id == 374) echo "selected=\"selected\"";
echo ">No.374 - 山羊宮‧杜門 （6星）</option>";
echo "<option value=\"375\"";
if($id == 375) echo "selected=\"selected\"";
echo ">No.375 - 鬼魅舞者‧凱莉 （5星）</option>";
echo "<option value=\"376\"";
if($id == 376) echo "selected=\"selected\"";
echo ">No.376 - 水瓶宮‧凱莉 （6星）</option>";
echo "<option value=\"377\"";
if($id == 377) echo "selected=\"selected\"";
echo ">No.377 - 海浪騎士‧卡秋婭與拉維妮斯 （5星）</option>";
echo "<option value=\"378\"";
if($id == 378) echo "selected=\"selected\"";
echo ">No.378 - 雙魚宮‧卡秋婭與拉維妮斯 （6星）</option>";
echo "<option value=\"379\"";
if($id == 379) echo "selected=\"selected\"";
echo ">No.379 - 黃道星靈‧水 （4星）</option>";
echo "<option value=\"380\"";
if($id == 380) echo "selected=\"selected\"";
echo ">No.380 - 黃道星靈‧火 （4星）</option>";
echo "<option value=\"381\"";
if($id == 381) echo "selected=\"selected\"";
echo ">No.381 - 黃道星靈‧木 （4星）</option>";
echo "<option value=\"382\"";
if($id == 382) echo "selected=\"selected\"";
echo ">No.382 - 黃道星靈‧光 （4星）</option>";
echo "<option value=\"383\"";
if($id == 383) echo "selected=\"selected\"";
echo ">No.383 - 黃道星靈‧暗 （4星）</option>";
echo "<option value=\"384\"";
if($id == 384) echo "selected=\"selected\"";
echo ">No.384 - 占星者 （5星）</option>";
echo "<option value=\"385\"";
if($id == 385) echo "selected=\"selected\"";
echo ">No.385 - 見習小丑 （1星）</option>";
echo "<option value=\"386\"";
if($id == 386) echo "selected=\"selected\"";
echo ">No.386 - 無頭小丑 （3星）</option>";
echo "<option value=\"387\"";
if($id == 387) echo "selected=\"selected\"";
echo ">No.387 - 午夜之丑角 （5星）</option>";
echo "<option value=\"388\"";
if($id == 388) echo "selected=\"selected\"";
echo ">No.388 - 不懼的鬼戰士 （5星）</option>";
echo "<option value=\"389\"";
if($id == 389) echo "selected=\"selected\"";
echo ">No.389 - 屠龍者‧貝奧武夫 （6星）</option>";
echo "<option value=\"390\"";
if($id == 390) echo "selected=\"selected\"";
echo ">No.390 - 不仁的鬼鬥士 （5星）</option>";
echo "<option value=\"391\"";
if($id == 391) echo "selected=\"selected\"";
echo ">No.391 - 戰神‧阿基里斯 （6星）</option>";
echo "<option value=\"392\"";
if($id == 392) echo "selected=\"selected\"";
echo ">No.392 - 不幸的鬼騎士 （5星）</option>";
echo "<option value=\"393\"";
if($id == 393) echo "selected=\"selected\"";
echo ">No.393 - 薔薇雙槍‧迪爾姆德 （6星）</option>";
echo "<option value=\"394\"";
if($id == 394) echo "selected=\"selected\"";
echo ">No.394 - 不惑的鬼武士 （5星）</option>";
echo "<option value=\"395\"";
if($id == 395) echo "selected=\"selected\"";
echo ">No.395 - 遮那王‧源義經 （6星）</option>";
echo "<option value=\"396\"";
if($id == 396) echo "selected=\"selected\"";
echo ">No.396 - 不義的鬼將士 （5星）</option>";
echo "<option value=\"397\"";
if($id == 397) echo "selected=\"selected\"";
echo ">No.397 - 鬼神‧呂布 （6星）</option>";
echo "<option value=\"398\"";
if($id == 398) echo "selected=\"selected\"";
echo ">No.398 - 光輝萬年靈魂石 （6星）</option>";
echo "<option value=\"399\"";
if($id == 399) echo "selected=\"selected\"";
echo ">No.399 - 暴食史萊姆王 （6星）</option>";
echo "<option value=\"400\"";
if($id == 400) echo "selected=\"selected\"";
echo ">No.400 - 瘋頭 （6星）</option>";
echo "<option value=\"401\"";
if($id == 401) echo "selected=\"selected\"";
echo ">No.401 - 聖言歌姬‧妍 （6星）</option>";
echo "<option value=\"402\"";
if($id == 402) echo "selected=\"selected\"";
echo ">No.402 - 夜言歌姬‧希 （6星）</option>";
echo "<option value=\"403\"";
if($id == 403) echo "selected=\"selected\"";
echo ">No.403 - 波拉 （3星）</option>";
echo "<option value=\"404\"";
if($id == 404) echo "selected=\"selected\"";
echo ">No.404 - 奇美拉 （3星）</option>";
echo "<option value=\"405\"";
if($id == 405) echo "selected=\"selected\"";
echo ">No.405 - 潘 （3星）</option>";
echo "<option value=\"406\"";
if($id == 406) echo "selected=\"selected\"";
echo ">No.406 - 福魯斯 （3星）</option>";
echo "<option value=\"407\"";
if($id == 407) echo "selected=\"selected\"";
echo ">No.407 - 拉彌亞 （3星）</option>";
echo "<option value=\"408\"";
if($id == 408) echo "selected=\"selected\"";
echo ">No.408 - 大魔導士莫莉 （6星）</option>";
echo "<option value=\"409\"";
if($id == 409) echo "selected=\"selected\"";
echo ">No.409 - 龍焰騎士肖恩 （6星）</option>";
echo "<option value=\"410\"";
if($id == 410) echo "selected=\"selected\"";
echo ">No.410 - 大地霸主鄧肯 （6星）</option>";
echo "<option value=\"411\"";
if($id == 411) echo "selected=\"selected\"";
echo ">No.411 - 公爵奈寶尼 （6星）</option>";
echo "<option value=\"412\"";
if($id == 412) echo "selected=\"selected\"";
echo ">No.412 - 死靈魔導安多 （6星）</option>";
echo "<option value=\"413\"";
if($id == 413) echo "selected=\"selected\"";
echo ">No.413 - 蒼龍魂使 （5星）</option>";
echo "<option value=\"414\"";
if($id == 414) echo "selected=\"selected\"";
echo ">No.414 - 龍儀姬‧烏蘇拉 （6星）</option>";
echo "<option value=\"415\"";
if($id == 415) echo "selected=\"selected\"";
echo ">No.415 - 赤龍魂使 （5星）</option>";
echo "<option value=\"416\"";
if($id == 416) echo "selected=\"selected\"";
echo ">No.416 - 龍儀姬‧愛格德 （6星）</option>";
echo "<option value=\"417\"";
if($id == 417) echo "selected=\"selected\"";
echo ">No.417 - 青龍魂使 （5星）</option>";
echo "<option value=\"418\"";
if($id == 418) echo "selected=\"selected\"";
echo ">No.418 - 龍儀姬‧芭芭拉 （6星）</option>";
echo "<option value=\"419\"";
if($id == 419) echo "selected=\"selected\"";
echo ">No.419 - 光龍魂使 （5星）</option>";
echo "<option value=\"420\"";
if($id == 420) echo "selected=\"selected\"";
echo ">No.420 - 龍脈者‧安納 （6星）</option>";
echo "<option value=\"421\"";
if($id == 421) echo "selected=\"selected\"";
echo ">No.421 - 暗龍魂使 （5星）</option>";
echo "<option value=\"422\"";
if($id == 422) echo "selected=\"selected\"";
echo ">No.422 - 龍脈者‧諾瓦利斯 （6星）</option>";
echo "<option value=\"423\"";
if($id == 423) echo "selected=\"selected\"";
echo ">No.423 - 異域法眼 （1星）</option>";
echo "<option value=\"424\"";
if($id == 424) echo "selected=\"selected\"";
echo ">No.424 - 機關騎士 （3星）</option>";
echo "<option value=\"425\"";
if($id == 425) echo "selected=\"selected\"";
echo ">No.425 - 永劫碑文像 （5星）</option>";
echo "<option value=\"426\"";
if($id == 426) echo "selected=\"selected\"";
echo ">No.426 - 碧海萬年靈魂石 （5星）</option>";
echo "<option value=\"427\"";
if($id == 427) echo "selected=\"selected\"";
echo ">No.427 - 熾焰萬年靈魂石 （5星）</option>";
echo "<option value=\"428\"";
if($id == 428) echo "selected=\"selected\"";
echo ">No.428 - 大地萬年靈魂石 （5星）</option>";
echo "<option value=\"429\"";
if($id == 429) echo "selected=\"selected\"";
echo ">No.429 - 追憶旅人 （3星）</option>";
echo "<option value=\"430\"";
if($id == 430) echo "selected=\"selected\"";
echo ">No.430 - 號角手加拉爾 （5星）</option>";
echo "<option value=\"431\"";
if($id == 431) echo "selected=\"selected\"";
echo ">No.431 - 貪婪精靈女王 （6星）</option>";
echo "<option value=\"432\"";
if($id == 432) echo "selected=\"selected\"";
echo ">No.432 - 奪寶海盜 （5星）</option>";
echo "<option value=\"433\"";
if($id == 433) echo "selected=\"selected\"";
echo ">No.433 - 冰晶領航者‧奪寶海盜 （6星）</option>";
echo "<option value=\"434\"";
if($id == 434) echo "selected=\"selected\"";
echo ">No.434 - 紅纓武者 （5星）</option>";
echo "<option value=\"435\"";
if($id == 435) echo "selected=\"selected\"";
echo ">No.435 - 火靈之舞‧紅纓武者 （6星）</option>";
echo "<option value=\"436\"";
if($id == 436) echo "selected=\"selected\"";
echo ">No.436 - 捕風酋長 （5星）</option>";
echo "<option value=\"437\"";
if($id == 437) echo "selected=\"selected\"";
echo ">No.437 - 翡翠獵手‧捕風酋長 （6星）</option>";
echo "<option value=\"438\"";
if($id == 438) echo "selected=\"selected\"";
echo ">No.438 - 清泉守衛 （6星）</option>";
echo "<option value=\"439\"";
if($id == 439) echo "selected=\"selected\"";
echo ">No.439 - 炎鎧戰士 （6星）</option>";
echo "<option value=\"440\"";
if($id == 440) echo "selected=\"selected\"";
echo ">No.440 - 雁目射手 （6星）</option>";
echo "<option value=\"441\"";
if($id == 441) echo "selected=\"selected\"";
echo ">No.441 - 萬劍寵僕 （6星）</option>";
echo "<option value=\"442\"";
if($id == 442) echo "selected=\"selected\"";
echo ">No.442 - 暗影鬥士 （6星）</option>";
echo "<option value=\"443\"";
if($id == 443) echo "selected=\"selected\"";
echo ">No.443 - 占星蛙法師 （3星）</option>";
echo "<option value=\"444\"";
if($id == 444) echo "selected=\"selected\"";
echo ">No.444 - 道法飄蟲 （3星）</option>";
echo "<option value=\"445\"";
if($id == 445) echo "selected=\"selected\"";
echo ">No.445 - 修道雛鴨 （3星）</option>";
echo "<option value=\"446\"";
if($id == 446) echo "selected=\"selected\"";
echo ">No.446 - 賜福蜜蜂 （3星）</option>";
echo "<option value=\"447\"";
if($id == 447) echo "selected=\"selected\"";
echo ">No.447 - 奧秘魚術士 （3星）</option>";
echo "<option value=\"448\"";
if($id == 448) echo "selected=\"selected\"";
echo ">No.448 - 符靈典範‧綠茵國王 （6星）</option>";
echo "<option value=\"449\"";
if($id == 449) echo "selected=\"selected\"";
echo ">No.449 - 狂怒蜥蜴暴君 （6星）</option>";
echo "<option value=\"450\"";
if($id == 450) echo "selected=\"selected\"";
echo ">No.450 - 法則女神 ‧ 姬氏 （6星）</option>";
echo "<option value=\"451\"";
if($id == 451) echo "selected=\"selected\"";
echo ">No.451 - 地精絞殺者 （4星）</option>";
echo "<option value=\"452\"";
if($id == 452) echo "selected=\"selected\"";
echo ">No.452 - 地精斬首者 （4星）</option>";
echo "<option value=\"453\"";
if($id == 453) echo "selected=\"selected\"";
echo ">No.453 - 地精扼喉者 （4星）</option>";
echo "<option value=\"454\"";
if($id == 454) echo "selected=\"selected\"";
echo ">No.454 - 地精碎骨者 （4星）</option>";
echo "<option value=\"455\"";
if($id == 455) echo "selected=\"selected\"";
echo ">No.455 - 地精切裂者 （4星）</option>";
echo "<option value=\"456\"";
if($id == 456) echo "selected=\"selected\"";
echo ">No.456 - 星佑法師愛莉絲 （4星）</option>";
echo "<option value=\"457\"";
if($id == 457) echo "selected=\"selected\"";
echo ">No.457 - 管狐飼者瑪莉曼 （4星）</option>";
echo "<option value=\"458\"";
if($id == 458) echo "selected=\"selected\"";
echo ">No.458 - 煉屍術士凱莉絲 （4星）</option>";
echo "<option value=\"459\"";
if($id == 459) echo "selected=\"selected\"";
echo ">No.459 - 神罰使者安迪莉亞 （4星）</option>";
echo "<option value=\"460\"";
if($id == 460) echo "selected=\"selected\"";
echo ">No.460 - 鍊金巫師莉莉絲 （4星）</option>";
echo "<option value=\"461\"";
if($id == 461) echo "selected=\"selected\"";
echo ">No.461 - 冽霜武僧 （4星）</option>";
echo "<option value=\"462\"";
if($id == 462) echo "selected=\"selected\"";
echo ">No.462 - 岩焰統領 （4星）</option>";
echo "<option value=\"463\"";
if($id == 463) echo "selected=\"selected\"";
echo ">No.463 - 木靈栽者 （4星）</option>";
echo "<option value=\"464\"";
if($id == 464) echo "selected=\"selected\"";
echo ">No.464 - 聖裁勇者 （4星）</option>";
echo "<option value=\"465\"";
if($id == 465) echo "selected=\"selected\"";
echo ">No.465 - 暗影刺客 （4星）</option>";
echo "<option value=\"466\"";
if($id == 466) echo "selected=\"selected\"";
echo ">No.466 - 貴族伊莉莎白 （5星）</option>";
echo "<option value=\"467\"";
if($id == 467) echo "selected=\"selected\"";
echo ">No.467 - 血浴美人 ‧ 伊莉莎白 （6星）</option>";
echo "<option value=\"468\"";
if($id == 468) echo "selected=\"selected\"";
echo ">No.468 - 信差潔琪 （5星）</option>";
echo "<option value=\"469\"";
if($id == 469) echo "selected=\"selected\"";
echo ">No.469 - 彈簧腿 ‧ 潔琪 （6星）</option>";
echo "<option value=\"470\"";
if($id == 470) echo "selected=\"selected\"";
echo ">No.470 - 婚約者貝莉 （5星）</option>";
echo "<option value=\"471\"";
if($id == 471) echo "selected=\"selected\"";
echo ">No.471 - 罌花新娘 ‧ 貝莉 （6星）</option>";
echo "<option value=\"472\"";
if($id == 472) echo "selected=\"selected\"";
echo ">No.472 - 紳士傑克 （5星）</option>";
echo "<option value=\"473\"";
if($id == 473) echo "selected=\"selected\"";
echo ">No.473 - 開膛怪傑 ‧ 傑克 （6星）</option>";
echo "<option value=\"474\"";
if($id == 474) echo "selected=\"selected\"";
echo ">No.474 - 理髮魔偶陶德 （5星）</option>";
echo "<option value=\"475\"";
if($id == 475) echo "selected=\"selected\"";
echo ">No.475 - 戲謔小丑 ‧ 陶德 （6星）</option>";
echo "<option value=\"476\"";
if($id == 476) echo "selected=\"selected\"";
echo ">No.476 - 冰雪巫師 ‧ 波葛 （5星）</option>";
echo "<option value=\"477\"";
if($id == 477) echo "selected=\"selected\"";
echo ">No.477 - 惡作劇精靈 ‧ 波加特 （5星）</option>";
echo "<option value=\"478\"";
if($id == 478) echo "selected=\"selected\"";
echo ">No.478 - 掃除小精靈 ‧ 布朗尼 （5星）</option>";
echo "<option value=\"479\"";
if($id == 479) echo "selected=\"selected\"";
echo ">No.479 - 沉思的賢者 ‧ 山特古羅斯 （6星）</option>";
echo "<option value=\"480\"";
if($id == 480) echo "selected=\"selected\"";
echo ">No.480 - 色慾胎飼魔母 （6星）</option>";
echo "<option value=\"481\"";
if($id == 481) echo "selected=\"selected\"";
echo ">No.481 - 記憶與遺忘‧女武神烏爾德 （6星）</option>";
echo "<option value=\"482\"";
if($id == 482) echo "selected=\"selected\"";
echo ">No.482 - 開端與終結‧女武神斯庫爾德 （6星）</option>";
echo "<option value=\"483\"";
if($id == 483) echo "selected=\"selected\"";
echo ">No.483 - 命定與改變‧女武神薇兒丹蒂 （6星）</option>";
echo "<option value=\"484\"";
if($id == 484) echo "selected=\"selected\"";
echo ">No.484 - 神木之眷‧永祭之伊登 （6星）</option>";
echo "<option value=\"485\"";
if($id == 485) echo "selected=\"selected\"";
echo ">No.485 - 破刃之鐮‧布倫希爾德 （6星）</option>";
echo "<option value=\"486\"";
if($id == 486) echo "selected=\"selected\"";
echo ">No.486 - 水龍牙棋 （3星）</option>";
echo "<option value=\"487\"";
if($id == 487) echo "selected=\"selected\"";
echo ">No.487 - 火龍牙棋 （3星）</option>";
echo "<option value=\"488\"";
if($id == 488) echo "selected=\"selected\"";
echo ">No.488 - 木龍牙棋 （3星）</option>";
echo "<option value=\"489\"";
if($id == 489) echo "selected=\"selected\"";
echo ">No.489 - 光龍牙棋 （3星）</option>";
echo "<option value=\"490\"";
if($id == 490) echo "selected=\"selected\"";
echo ">No.490 - 暗龍牙棋 （3星）</option>";
echo "<option value=\"491\"";
if($id == 491) echo "selected=\"selected\"";
echo ">No.491 - 仰望者瘋帽 （6星）</option>";
echo "<option value=\"492\"";
if($id == 492) echo "selected=\"selected\"";
echo ">No.492 - 狂人三月兔 （6星）</option>";
echo "<option value=\"493\"";
if($id == 493) echo "selected=\"selected\"";
echo ">No.493 - 建言者書頁蟲 （6星）</option>";
echo "<option value=\"494\"";
if($id == 494) echo "selected=\"selected\"";
echo ">No.494 - 餐桌騎士睡鼠 （6星）</option>";
echo "<option value=\"495\"";
if($id == 495) echo "selected=\"selected\"";
echo ">No.495 - 魔郡咧齒貓 （6星）</option>";
echo "<option value=\"496\"";
if($id == 496) echo "selected=\"selected\"";
echo ">No.496 - 魔境之主 紅心女王 （6星）</option>";
echo "<option value=\"497\"";
if($id == 497) echo "selected=\"selected\"";
echo ">No.497 - 笑容守護犬 （5星）</option>";
echo "<option value=\"498\"";
if($id == 498) echo "selected=\"selected\"";
echo ">No.498 - 福德神寵 ‧ 笑犬 （6星）</option>";
echo "<option value=\"499\"";
if($id == 499) echo "selected=\"selected\"";
echo ">No.499 - 怒顏守護犬 （5星）</option>";
echo "<option value=\"500\"";
if($id == 500) echo "selected=\"selected\"";
echo ">No.500 - 懲惡神衛 ‧ 怒犬 （6星）</option>";
echo "<option value=\"501\"";
if($id == 501) echo "selected=\"selected\"";
echo ">No.501 - 韶光仙獸 ‧ 年 （6星）</option>";
echo "<option value=\"502\"";
if($id == 502) echo "selected=\"selected\"";
echo ">No.502 - 覓果幻獸 （5星）</option>";
echo "<option value=\"503\"";
if($id == 503) echo "selected=\"selected\"";
echo ">No.503 - 原始滄龍 （0星）</option>";
echo "<option value=\"504\"";
if($id == 504) echo "selected=\"selected\"";
echo ">No.504 -  （0星）</option>";
echo "<option value=\"505\"";
if($id == 505) echo "selected=\"selected\"";
echo ">No.505 -  （0星）</option>";
echo "<option value=\"506\"";
if($id == 506) echo "selected=\"selected\"";
echo ">No.506 - 不滅戰意‧費雷 （7星）</option>";
echo "<option value=\"507\"";
if($id == 507) echo "selected=\"selected\"";
echo ">No.507 - 烈火懲責‧提爾 （7星）</option>";
echo "<option value=\"508\"";
if($id == 508) echo "selected=\"selected\"";
echo ">No.508 - 唁魂之喚‧費蕾雅 （7星）</option>";
echo "<option value=\"509\"";
if($id == 509) echo "selected=\"selected\"";
echo ">No.509 - 轟雷鳴動‧索爾 （7星）</option>";
echo "<option value=\"510\"";
if($id == 510) echo "selected=\"selected\"";
echo ">No.510 - 不赦眚惡‧洛基 （7星）</option>";
echo "<option value=\"511\"";
if($id == 511) echo "selected=\"selected\"";
echo ">No.511 - 乾坎天帝‧青龍 （6星）</option>";
echo "<option value=\"512\"";
if($id == 512) echo "selected=\"selected\"";
echo ">No.512 - 坎艮神鳥‧朱雀 （6星）</option>";
echo "<option value=\"513\"";
if($id == 513) echo "selected=\"selected\"";
echo ">No.513 - 震巽靈帝‧玄武 （6星）</option>";
echo "<option value=\"514\"";
if($id == 514) echo "selected=\"selected\"";
echo ">No.514 - 离坤獸皇‧白虎 （6星）</option>";
echo "<option value=\"515\"";
if($id == 515) echo "selected=\"selected\"";
echo ">No.515 - 兌中邪帝‧饕餮 （6星）</option>";
echo "<option value=\"516\"";
if($id == 516) echo "selected=\"selected\"";
echo ">No.516 - 復活火鳥 （2星）</option>";
echo "<option value=\"517\"";
if($id == 517) echo "selected=\"selected\"";
echo ">No.517 - 魅影劍客 （3星）</option>";
echo "<option value=\"518\"";
if($id == 518) echo "selected=\"selected\"";
echo ">No.518 - 靈光飛刀手 （4星）</option>";
echo "<option value=\"519\"";
if($id == 519) echo "selected=\"selected\"";
echo ">No.519 - 生命之光‧伊施妲 （6星）</option>";
echo "<option value=\"520\"";
if($id == 520) echo "selected=\"selected\"";
echo ">No.520 - 傲慢幽狼酋長 （6星）</option>";
echo "<option value=\"521\"";
if($id == 521) echo "selected=\"selected\"";
echo ">No.521 - 蝦兵‧蟹將 （3星）</option>";
echo "<option value=\"522\"";
if($id == 522) echo "selected=\"selected\"";
echo ">No.522 - 甲兵‧鎧將 （4星）</option>";
echo "<option value=\"523\"";
if($id == 523) echo "selected=\"selected\"";
echo ">No.523 - 修道客 （3星）</option>";
echo "<option value=\"524\"";
if($id == 524) echo "selected=\"selected\"";
echo ">No.524 - 崑崙道士 （4星）</option>";
echo "<option value=\"525\"";
if($id == 525) echo "selected=\"selected\"";
echo ">No.525 - 桃木精 （3星）</option>";
echo "<option value=\"526\"";
if($id == 526) echo "selected=\"selected\"";
echo ">No.526 - 千里眼 （4星）</option>";
echo "<option value=\"527\"";
if($id == 527) echo "selected=\"selected\"";
echo ">No.527 - 尋道者 （3星）</option>";
echo "<option value=\"528\"";
if($id == 528) echo "selected=\"selected\"";
echo ">No.528 - 散仙神女 （4星）</option>";
echo "<option value=\"529\"";
if($id == 529) echo "selected=\"selected\"";
echo ">No.529 - 柳鬼 （3星）</option>";
echo "<option value=\"530\"";
if($id == 530) echo "selected=\"selected\"";
echo ">No.530 - 順風耳 （4星）</option>";
echo "<option value=\"531\"";
if($id == 531) echo "selected=\"selected\"";
echo ">No.531 - 太師聞仲 （5星）</option>";
echo "<option value=\"532\"";
if($id == 532) echo "selected=\"selected\"";
echo ">No.532 - 普化天尊‧聞仲 （6星）</option>";
echo "<option value=\"533\"";
if($id == 533) echo "selected=\"selected\"";
echo ">No.533 - 道僧燃燈 （5星）</option>";
echo "<option value=\"534\"";
if($id == 534) echo "selected=\"selected\"";
echo ">No.534 - 錠光如來‧燃燈 （6星）</option>";
echo "<option value=\"535\"";
if($id == 535) echo "selected=\"selected\"";
echo ">No.535 - 靈將楊戩 （5星）</option>";
echo "<option value=\"536\"";
if($id == 536) echo "selected=\"selected\"";
echo ">No.536 - 清源仙將‧楊戩 （6星）</option>";
echo "<option value=\"537\"";
if($id == 537) echo "selected=\"selected\"";
echo ">No.537 - 仙道姜尚 （5星）</option>";
echo "<option value=\"538\"";
if($id == 538) echo "selected=\"selected\"";
echo ">No.538 - 封神仙帥‧姜子牙 （6星）</option>";
echo "<option value=\"539\"";
if($id == 539) echo "selected=\"selected\"";
echo ">No.539 - 仙道申公豹 （5星）</option>";
echo "<option value=\"540\"";
if($id == 540) echo "selected=\"selected\"";
echo ">No.540 - 號雷鬥罡‧申公豹 （6星）</option>";
echo "<option value=\"541\"";
if($id == 541) echo "selected=\"selected\"";
echo ">No.541 - 傀儡仙童 （5星）</option>";
echo "<option value=\"542\"";
if($id == 542) echo "selected=\"selected\"";
echo ">No.542 - 三清祖師‧元始天尊 （6星）</option>";
echo "<option value=\"543\"";
if($id == 543) echo "selected=\"selected\"";
echo ">No.543 - 靈寶天尊‧通天教主 （6星）</option>";
echo "<option value=\"544\"";
if($id == 544) echo "selected=\"selected\"";
echo ">No.544 - 異界使者 （0星）</option>";
echo "<option value=\"545\"";
if($id == 545) echo "selected=\"selected\"";
echo ">No.545 - 腫脹之女 （0星）</option>";
echo "<option value=\"546\"";
if($id == 546) echo "selected=\"selected\"";
echo ">No.546 - 諾弗‧刻 （3星）</option>";
echo "<option value=\"547\"";
if($id == 547) echo "selected=\"selected\"";
echo ">No.547 - 腹蛇異兵 （3星）</option>";
echo "<option value=\"548\"";
if($id == 548) echo "selected=\"selected\"";
echo ">No.548 - 異神之胎 （3星）</option>";
echo "<option value=\"549\"";
if($id == 549) echo "selected=\"selected\"";
echo ">No.549 - 銀曉信徒 （3星）</option>";
echo "<option value=\"550\"";
if($id == 550) echo "selected=\"selected\"";
echo ">No.550 - 噬土魔蟲 （3星）</option>";
echo "<option value=\"551\"";
if($id == 551) echo "selected=\"selected\"";
echo ">No.551 - 深潛的異族 （5星）</option>";
echo "<option value=\"552\"";
if($id == 552) echo "selected=\"selected\"";
echo ">No.552 - 深潛者之僕‧蟆鰣 （6星）</option>";
echo "<option value=\"553\"";
if($id == 553) echo "selected=\"selected\"";
echo ">No.553 - 魔焰吸血鬼 （5星）</option>";
echo "<option value=\"554\"";
if($id == 554) echo "selected=\"selected\"";
echo ">No.554 - 永焰之渴‧唐納德 （6星）</option>";
echo "<option value=\"555\"";
if($id == 555) echo "selected=\"selected\"";
echo ">No.555 - 巨蟾異獸 （5星）</option>";
echo "<option value=\"556\"";
if($id == 556) echo "selected=\"selected\"";
echo ">No.556 - 食魂魔蟾‧札特瓜 （6星）</option>";
echo "<option value=\"557\"";
if($id == 557) echo "selected=\"selected\"";
echo ">No.557 - 幻神化身 （5星）</option>";
echo "<option value=\"558\"";
if($id == 558) echo "selected=\"selected\"";
echo ">No.558 - 幻夢古神‧諾斯登 （6星）</option>";
echo "<option value=\"559\"";
if($id == 559) echo "selected=\"selected\"";
echo ">No.559 - 異域蟲族 （5星）</option>";
echo "<option value=\"560\"";
if($id == 560) echo "selected=\"selected\"";
echo ">No.560 - 門鑰之僕‧米戈 （6星）</option>";
echo "<option value=\"561\"";
if($id == 561) echo "selected=\"selected\"";
echo ">No.561 - 奈亞拉托提普 （0星）</option>";
echo "<option value=\"562\"";
if($id == 562) echo "selected=\"selected\"";
echo ">No.562 - 黃衣魅影‧哈斯塔 （6星）</option>";
echo "<option value=\"563\"";
if($id == 563) echo "selected=\"selected\"";
echo ">No.563 - 負罪役夫尼祿 （0星）</option>";
}
